In [1]:
# Dependencies
import pandas as pd
from pandas import Series,DataFrame
import numpy as np
import pymongo
import time 
from IPython import get_ipython
import nbconvert

Read in Table from URL as Data Frame

In [2]:
rep_url = 'https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States_by_population'

df = pd.read_html(rep_url)[0]
df

      Rank                                              State  \
   Current  2010                                        State
0      1.0   1.0                                   California
1      2.0   2.0                                        Texas
2      3.0   4.0                                      Florida
3      4.0   3.0                                     New York
4      5.0   6.0                                 Pennsylvania
5      6.0   5.0                                     Illinois
6      7.0   9.0                                      Georgia
7      8.0  10.0                               North Carolina
8      9.0   7.0                                         Ohio
9     10.0   8.0                                     Michigan
10    11.0  11.0                                   New Jersey
11    12.0  12.0                                     Virginia
12    13.0  13.0                                   Washington
13    14.0  16.0                                      Arizona
14    15.0  14.0                                Massachusetts
15    16.0  17.0                                    Tennessee
16    17.0  15.0                                      Indiana
17    18.0  18.0                                     Missouri
18    19.0  19.0                                     Maryland
19    20.0  20.0                                    Wisconsin
20    21.0  22.0                                     Colorado
21    22.0  21.0                                    Minnesota
22    23.0  24.0                               South Carolina
23    24.0  23.0                                      Alabama
24    25.0  25.0                                    Louisiana
25    26.0  26.0                                     Kentucky
26    27.0  27.0                                       Oregon
27    28.0  28.0                                     Oklahoma
28    29.0  30.0                                  Connecticut
29    30.0  35.0                                         Utah
30    31.0  29.0                                  Puerto Rico
31    32.0  31.0                                         Iowa
32    33.0  36.0                                       Nevada
33    34.0  33.0                                     Arkansas
34    35.0  32.0                                  Mississippi
35    36.0  34.0                                       Kansas
36    37.0  37.0                                   New Mexico
37    38.0  39.0                                     Nebraska
38    39.0  38.0                                West Virginia
39    40.0  40.0                                        Idaho
40    41.0  41.0                                       Hawaii
41    42.0  43.0                                New Hampshire
42    43.0  42.0                                        Maine
43    44.0  45.0                                      Montana
44    45.0  44.0                                 Rhode Island
45    46.0  46.0                                     Delaware
46    47.0  47.0                                 South Dakota
47    48.0  49.0                                 North Dakota
48    49.0  48.0                                       Alaska
49    50.0  51.0                         District of Columbia
50    51.0  50.0                                      Vermont
51    52.0  52.0                                      Wyoming
52    53.0  53.0                                         Guam
53    54.0  54.0                          U.S. Virgin Islands
54    55.0  56.0                     Northern Mariana Islands
55    56.0  55.0                               American Samoa
56     NaN   NaN                     Contiguous United States
57     NaN   NaN                             The fifty states
58     NaN   NaN                          Fifty states + D.C.
59     NaN   NaN  Total U.S. (including D.C. and territories)

           Census population                  Change, 2010–2019               \
   Estimate, July 1, 2020[8] April 1, 2010[9]   Percent[note 2]     Absolute
0                   39512223         37253956              6.1%   +2,257,700
1                   28995881         25145561             15.3%   +3,850,320
2                   21477737         18801310             14.2%   +2,676,427
3                   19453561         19378102              0.4%      +75,459
4                   12801989         12702379              0.8%      +99,610
5                   12671821         12830632             –1.2%     –158,811
6                   11689100          9536504             10.3%   +2,152,596
7                   11609423          9471653              9.9%   +2,137,770
8                   11580084         11486483              1.2%     +123,908
9                   10198857          9883640             1.04%     +103,217
10                   9209190          8791894             1.03%      +90,296
11                   8960519          8001024              6.7%     +534,495
12                   7614893          6724540             13.2%     +890,353
13                   7078717          6392017             13.9%     +886,700
14                   6892503          6547629              5.3%     +344,874
15                   6829174          6346105              7.6%     +483,069
16                   6732219          6483802              3.8%     +248,417
17                   6188428          5988927             2.48%     +148,501
18                   6155680          5773552              4.7%     +272,128
19                   5822434          5686986              2.4%     +135,448
20                   5758736          5029196             14.5%     +729,540
21                   5639632          5303925              6.3%     +335,707
22                   5127714          4625364             11.3%     +523,350
23                   4653423          4779736              2.6%     +123,449
24                   4648794          4533372            2.546%     +115,422
25                   4467673          4339367             2.96%     +128,306
26                   4217737          3831074             10.1%     +386,663
27                   3956971          3751351              5.5%     +205,620
28                   3565287          3574097             –0.2%       –8,810
29                   3205958          2763885             16.0%     +442,073
30                   3193694          3725789            –14.3%     –532,095
31                   3155070          3046355              3.6%     +108,715
32                   3080156          2700551             14.1%     +379,605
33                   3017804          2915918              3.5%     +101,886
34                   2976149          2967297              0.3%       +8,852
35                   2913314          2853118              2.1%      +60,196
36                   2096829          2059179              1.8%      +37,650
37                   1934408          1826341              5.9%     +108,067
38                   1792147          1852994             –3.3%      –60,847
39                   1787065          1567582             14.0%     +219,483
40                   1415872          1360301              4.1%      +55,571
41                   1359711          1316470              3.3%      +43,241
42                   1344212          1328361              1.2%      +15,851
43                   1068778           989415              8.0%      +79,363
44                   1059361          1052567              0.6%       +6,794
45                    973764           897934              8.4%      +75,830
46                    884659           814180              8.7%      +70,479
47                    762062           672591             13.3%      +89,471
48                    731545           710231             3.00%      +21,314
49                    705749           601723             17.3%     +104,026
50                    623989           625741             –0.3%       –1,752
51                    578759           563626              2.7%      +15,133
52               168,485[10]      159,358[11]             5.73%       +9,127
53               106,235[12]      106,405[13]            –0.16%         –170
54                51,433[14]       53,883[15]            –4.55%       –2,450
55                49,437[16]       55,519[17]           –10.95%       –6,082
56                 325386357        306675006              6.2%  +19,011,351
57                 327533795        308143836              6.3%  +19,389,959
58                 328239523        308745538              6.3%  +19,493,985
59                 331808807        312846492              6.1%  +18,962,315

   Total U.S. House of Representatives Seats  \
   Total U.S. House of Representatives Seats
0                                         53
1                                         36
2                                         27
3                                         27
4                                         18
5                                         18
6                                         14
7                                         13
8                                         16
9                                         14
10                                        12
11                                        11
12                                        10
13                                         9
14                                         9
15                                         9
16                                         9
17                                         8
18                                         8
19                                         8
20                                         7
21                                         8
22                                         7
23                                         7
24                                         6
25                                         6
26                                         5
27                                         5
28                                         5
29                                         4
30                            1 (non-voting)
31                                         4
32                                         4
33                                         4
34                                         4
35                                         4
36                                         3
37                                         3
38                                         3
39                                         2
40                                         2
41                                         2
42                                         2
43                                         1
44                                         2
45                                         1
46                                         1
47                                         1
48                                         1
49                            1 (non-voting)
50                                         1
51                                         1
52                            1 (non-voting)
53                            1 (non-voting)
54                            1 (non-voting)
55                            1 (non-voting)
56                                       432
57                                       435
58                      435 (+ 1 non-voting)
59                      435 (+ 6 non-voting)

   Estimated population per electoral vote, 2019[note 1]
   Estimated population per electoral vote, 2019[note 1]
0                                              718404
1                                              763050
2                                              740611
3                                              670812
4                                              640099
5                                              633591
6                                              649394
7                                              663589
8                                              699206
9                                              624179
10                                             634442
11                                             656578
12                                             634574
13                                             661702
14                                             626591
15                                             620834
16                                             612020
17                                             613743
18                                             604568
19                                             582243
20                                             639860
21                                             563963
22                                             572079
23                                             544798
24                                             581099
25                                             558459
26                                             602534
27                                             565282
28                                             509327
29                                             534326
30                                                  —
31                                             525845
32                                             513359
33                                             502967
34                                             496024
35                                             485552
36                                             419366
37                                             386882
38                                             358435
39                                             446516
40                                             353968
41                                             339928
42                                             336053
43                                             356259
44                                             264840
45                                             324588
46                                             294886
47                                             254021
48                                             243848
49                                             235250
50                                             207996
51                                             192920
52                                                  —
53                                                  —
54                                                  —
55                                                  —
56                                             616262
57                                             612213
58                                             610111
59                                                  —

Flatten Multi-Level Index

In [3]:
df.columns = df.columns.get_level_values(0)

#df.columns = [' '.join(col).strip() for col in df.columns.values]

df

,Rank,Rank,State,Census population,Census population,"Change, 2010–2019","Change, 2010–2019",Total U.S. House of Representatives Seats,"Estimated population per electoral vote, 2019[note 1]"
0,1.0,1.0,California,39512223,37253956,6.1%,"+2,257,700",53,718404
1,2.0,2.0,Texas,28995881,25145561,15.3%,"+3,850,320",36,763050
2,3.0,4.0,Florida,21477737,18801310,14.2%,"+2,676,427",27,740611
3,4.0,3.0,New York,19453561,19378102,0.4%,"+75,459",27,670812
4,5.0,6.0,Pennsylvania,12801989,12702379,0.8%,"+99,610",18,640099
5,6.0,5.0,Illinois,12671821,12830632,–1.2%,"–158,811",18,633591
6,7.0,9.0,Georgia,11689100,9536504,10.3%,"+2,152,596",14,649394
7,8.0,10.0,North Carolina,11609423,9471653,9.9%,"+2,137,770",13,663589
8,9.0,7.0,Ohio,11580084,11486483,1.2%,"+123,908",16,699206
9,10.0,8.0,Michigan,10198857,9883640,1.04%,"+103,217",14,624179
10,11.0,11.0,New Jersey,9209190,8791894,1.03%,"+90,296",12,634442
11,12.0,12.0,Virginia,8960519,8001024,6.7%,"+534,495",11,656578
12,13.0,13.0,Washington,7614893,6724540,13.2%,"+890,353",10,634574
13,14.0,16.0,Arizona,7078717,6392017,13.9%,"+886,700",9,661702
14,15.0,14.0,Massachusetts,6892503,6547629,5.3%,"+344,874",9,626591
15,16.0,17.0,Tennessee,6829174,6346105,7.6%,"+483,069",9,620834
16,17.0,15.0,Indiana,6732219,6483802,3.8%,"+248,417",9,612020
17,18.0,18.0,Missouri,6188428,5988927,2.48%,"+148,501",8,613743
18,19.0,19.0,Maryland,6155680,5773552,4.7%,"+272,128",8,604568
19,20.0,20.0,Wisconsin,5822434,5686986,2.4%,"+135,448",8,582243
20,21.0,22.0,Colorado,5758736,5029196,14.5%,"+729,540",7,639860
21,22.0,21.0,Minnesota,5639632,5303925,6.3%,"+335,707",8,563963
22,23.0,24.0,South Carolina,5127714,4625364,11.3%,"+523,350",7,572079
23,24.0,23.0,Alabama,4653423,4779736,2.6%,"+123,449",7,544798
24,25.0,25.0,Louisiana,4648794,4533372,2.546%,"+115,422",6,581099
25,26.0,26.0,Kentucky,4467673,4339367,2.96%,"+128,306",6,558459
26,27.0,27.0,Oregon,4217737,3831074,10.1%,"+386,663",5,602534
27,28.0,28.0,Oklahoma,3956971,3751351,5.5%,"+205,620",5,565282
28,29.0,30.0,Connecticut,3565287,3574097,–0.2%,"–8,810",5,509327
29,30.0,35.0,Utah,3205958,2763885,16.0%,"+442,073",4,534326
30,31.0,29.0,Puerto Rico,3193694,3725789,–14.3%,"–532,095",1 (non-voting),—
31,32.0,31.0,Iowa,3155070,3046355,3.6%,"+108,715",4,525845
32,33.0,36.0,Nevada,3080156,2700551,14.1%,"+379,605",4,513359
33,34.0,33.0,Arkansas,3017804,2915918,3.5%,"+101,886",4,502967
34,35.0,32.0,Mississippi,2976149,2967297,0.3%,"+8,852",4,496024
35,36.0,34.0,Kansas,2913314,2853118,2.1%,"+60,196",4,485552
36,37.0,37.0,New Mexico,2096829,2059179,1.8%,"+37,650",3,419366
37,38.0,39.0,Nebraska,1934408,1826341,5.9%,"+108,067",3,386882
38,39.0,38.0,West Virginia,1792147,1852994,–3.3%,"–60,847",3,358435
39,40.0,40.0,Idaho,1787065,1567582,14.0%,"+219,483",2,446516
40,41.0,41.0,Hawaii,1415872,1360301,4.1%,"+55,571",2,353968
41,42.0,43.0,New Hampshire,1359711,1316470,3.3%,"+43,241",2,339928
42,43.0,42.0,Maine,1344212,1328361,1.2%,"+15,851",2,336053
43,44.0,45.0,Montana,1068778,989415,8.0%,"+79,363",1,356259
44,45.0,44.0,Rhode Island,1059361,1052567,0.6%,"+6,794",2,264840
45,46.0,46.0,Delaware,973764,897934,8.4%,"+75,830",1,324588
46,47.0,47.0,South Dakota,884659,814180,8.7%,"+70,479",1,294886
47,48.0,49.0,North Dakota,762062,672591,13.3%,"+89,471",1,254021
48,49.0,48.0,Alaska,731545,710231,3.00%,"+21,314",1,243848
49,50.0,51.0,District of Columbia,705749,601723,17.3%,"+104,026",1 (non-voting),235250
50,51.0,50.0,Vermont,623989,625741,–0.3%,"–1,752",1,207996
51,52.0,52.0,Wyoming,578759,563626,2.7%,"+15,133",1,192920
52,53.0,53.0,Guam,"168,485[10]","159,358[11]",5.73%,"+9,127",1 (non-voting),—
53,54.0,54.0,U.S. Virgin Islands,"106,235[12]","106,405[13]",–0.16%,–170,1 (non-voting),—
54,55.0,56.0,Northern Mariana Islands,"51,433[14]","53,883[15]",–4.55%,"–2,450",1 (non-voting),—
55,56.0,55.0,American Samoa,"49,437[16]","55,519[17]",–10.95%,"–6,082",1 (non-voting),—
56,NaN,NaN,Contiguous United States,325386357,306675006,6.2%,"+19,011,351",432,616262
57,NaN,NaN,The fifty states,327533795,308143836,6.3%,"+19,389,959",435,612213
58,NaN,NaN,Fifty states + D.C.,328239523,308745538,6.3%,"+19,493,985",435 (+ 1 non-voting),610111
59,NaN,NaN,Total U.S. (including D.C. and territories),331808807,312846492,6.1%,"+18,962,315",435 (+ 6 non-voting),—

Select Relevant Columns

In [4]:
df = df[['State', 'Census population', 'Total U.S. House of Representatives Seats']]
df

,State,Census population,Census population,Total U.S. House of Representatives Seats
0,California,39512223,37253956,53
1,Texas,28995881,25145561,36
2,Florida,21477737,18801310,27
3,New York,19453561,19378102,27
4,Pennsylvania,12801989,12702379,18
5,Illinois,12671821,12830632,18
6,Georgia,11689100,9536504,14
7,North Carolina,11609423,9471653,13
8,Ohio,11580084,11486483,16
9,Michigan,10198857,9883640,14
10,New Jersey,9209190,8791894,12
11,Virginia,8960519,8001024,11
12,Washington,7614893,6724540,10
13,Arizona,7078717,6392017,9
14,Massachusetts,6892503,6547629,9
15,Tennessee,6829174,6346105,9
16,Indiana,6732219,6483802,9
17,Missouri,6188428,5988927,8
18,Maryland,6155680,5773552,8
19,Wisconsin,5822434,5686986,8
20,Colorado,5758736,5029196,7
21,Minnesota,5639632,5303925,8
22,South Carolina,5127714,4625364,7
23,Alabama,4653423,4779736,7
24,Louisiana,4648794,4533372,6
25,Kentucky,4467673,4339367,6
26,Oregon,4217737,3831074,5
27,Oklahoma,3956971,3751351,5
28,Connecticut,3565287,3574097,5
29,Utah,3205958,2763885,4
30,Puerto Rico,3193694,3725789,1 (non-voting)
31,Iowa,3155070,3046355,4
32,Nevada,3080156,2700551,4
33,Arkansas,3017804,2915918,4
34,Mississippi,2976149,2967297,4
35,Kansas,2913314,2853118,4
36,New Mexico,2096829,2059179,3
37,Nebraska,1934408,1826341,3
38,West Virginia,1792147,1852994,3
39,Idaho,1787065,1567582,2
40,Hawaii,1415872,1360301,2
41,New Hampshire,1359711,1316470,2
42,Maine,1344212,1328361,2
43,Montana,1068778,989415,1
44,Rhode Island,1059361,1052567,2
45,Delaware,973764,897934,1
46,South Dakota,884659,814180,1
47,North Dakota,762062,672591,1
48,Alaska,731545,710231,1
49,District of Columbia,705749,601723,1 (non-voting)
50,Vermont,623989,625741,1
51,Wyoming,578759,563626,1
52,Guam,"168,485[10]","159,358[11]",1 (non-voting)
53,U.S. Virgin Islands,"106,235[12]","106,405[13]",1 (non-voting)
54,Northern Mariana Islands,"51,433[14]","53,883[15]",1 (non-voting)
55,American Samoa,"49,437[16]","55,519[17]",1 (non-voting)
56,Contiguous United States,325386357,306675006,432
57,The fifty states,327533795,308143836,435
58,Fifty states + D.C.,328239523,308745538,435 (+ 1 non-voting)
59,Total U.S. (including D.C. and territories),331808807,312846492,435 (+ 6 non-voting)

Rename 2010 Census Column to Address Duplicate Column Names

In [5]:
column_names = df.columns.values
column_names[2] = "2010 Census Population"
df.columns = column_names
df

,State,Census population,2010 Census Population,Total U.S. House of Representatives Seats
0,California,39512223,37253956,53
1,Texas,28995881,25145561,36
2,Florida,21477737,18801310,27
3,New York,19453561,19378102,27
4,Pennsylvania,12801989,12702379,18
5,Illinois,12671821,12830632,18
6,Georgia,11689100,9536504,14
7,North Carolina,11609423,9471653,13
8,Ohio,11580084,11486483,16
9,Michigan,10198857,9883640,14
10,New Jersey,9209190,8791894,12
11,Virginia,8960519,8001024,11
12,Washington,7614893,6724540,10
13,Arizona,7078717,6392017,9
14,Massachusetts,6892503,6547629,9
15,Tennessee,6829174,6346105,9
16,Indiana,6732219,6483802,9
17,Missouri,6188428,5988927,8
18,Maryland,6155680,5773552,8
19,Wisconsin,5822434,5686986,8
20,Colorado,5758736,5029196,7
21,Minnesota,5639632,5303925,8
22,South Carolina,5127714,4625364,7
23,Alabama,4653423,4779736,7
24,Louisiana,4648794,4533372,6
25,Kentucky,4467673,4339367,6
26,Oregon,4217737,3831074,5
27,Oklahoma,3956971,3751351,5
28,Connecticut,3565287,3574097,5
29,Utah,3205958,2763885,4
30,Puerto Rico,3193694,3725789,1 (non-voting)
31,Iowa,3155070,3046355,4
32,Nevada,3080156,2700551,4
33,Arkansas,3017804,2915918,4
34,Mississippi,2976149,2967297,4
35,Kansas,2913314,2853118,4
36,New Mexico,2096829,2059179,3
37,Nebraska,1934408,1826341,3
38,West Virginia,1792147,1852994,3
39,Idaho,1787065,1567582,2
40,Hawaii,1415872,1360301,2
41,New Hampshire,1359711,1316470,2
42,Maine,1344212,1328361,2
43,Montana,1068778,989415,1
44,Rhode Island,1059361,1052567,2
45,Delaware,973764,897934,1
46,South Dakota,884659,814180,1
47,North Dakota,762062,672591,1
48,Alaska,731545,710231,1
49,District of Columbia,705749,601723,1 (non-voting)
50,Vermont,623989,625741,1
51,Wyoming,578759,563626,1
52,Guam,"168,485[10]","159,358[11]",1 (non-voting)
53,U.S. Virgin Islands,"106,235[12]","106,405[13]",1 (non-voting)
54,Northern Mariana Islands,"51,433[14]","53,883[15]",1 (non-voting)
55,American Samoa,"49,437[16]","55,519[17]",1 (non-voting)
56,Contiguous United States,325386357,306675006,432
57,The fifty states,327533795,308143836,435
58,Fifty states + D.C.,328239523,308745538,435 (+ 1 non-voting)
59,Total U.S. (including D.C. and territories),331808807,312846492,435 (+ 6 non-voting)

Drop Estimated Unnecessary Estimated Population Column

In [6]:
df = df.drop(df.columns[1], axis=1)
df

,State,2010 Census Population,Total U.S. House of Representatives Seats
0,California,37253956,53
1,Texas,25145561,36
2,Florida,18801310,27
3,New York,19378102,27
4,Pennsylvania,12702379,18
5,Illinois,12830632,18
6,Georgia,9536504,14
7,North Carolina,9471653,13
8,Ohio,11486483,16
9,Michigan,9883640,14
10,New Jersey,8791894,12
11,Virginia,8001024,11
12,Washington,6724540,10
13,Arizona,6392017,9
14,Massachusetts,6547629,9
15,Tennessee,6346105,9
16,Indiana,6483802,9
17,Missouri,5988927,8
18,Maryland,5773552,8
19,Wisconsin,5686986,8
20,Colorado,5029196,7
21,Minnesota,5303925,8
22,South Carolina,4625364,7
23,Alabama,4779736,7
24,Louisiana,4533372,6
25,Kentucky,4339367,6
26,Oregon,3831074,5
27,Oklahoma,3751351,5
28,Connecticut,3574097,5
29,Utah,2763885,4
30,Puerto Rico,3725789,1 (non-voting)
31,Iowa,3046355,4
32,Nevada,2700551,4
33,Arkansas,2915918,4
34,Mississippi,2967297,4
35,Kansas,2853118,4
36,New Mexico,2059179,3
37,Nebraska,1826341,3
38,West Virginia,1852994,3
39,Idaho,1567582,2
40,Hawaii,1360301,2
41,New Hampshire,1316470,2
42,Maine,1328361,2
43,Montana,989415,1
44,Rhode Island,1052567,2
45,Delaware,897934,1
46,South Dakota,814180,1
47,North Dakota,672591,1
48,Alaska,710231,1
49,District of Columbia,601723,1 (non-voting)
50,Vermont,625741,1
51,Wyoming,563626,1
52,Guam,"159,358[11]",1 (non-voting)
53,U.S. Virgin Islands,"106,405[13]",1 (non-voting)
54,Northern Mariana Islands,"53,883[15]",1 (non-voting)
55,American Samoa,"55,519[17]",1 (non-voting)
56,Contiguous United States,306675006,432
57,The fifty states,308143836,435
58,Fifty states + D.C.,308745538,435 (+ 1 non-voting)
59,Total U.S. (including D.C. and territories),312846492,435 (+ 6 non-voting)

Replace Values for House of Representatives Seats w/ NaN for non-State Rows and Drop NaNs

In [7]:
representation_df = df.replace({'1 (non-voting)': np.NaN, '435 (+ 1 non-voting)': np.NaN, '435 (+ 6 non-voting)': np.NaN, 
                         '432': np.NaN, '435': np.NaN})

representation_df = representation_df.dropna()
representation_df

,State,2010 Census Population,Total U.S. House of Representatives Seats
0,California,37253956,53
1,Texas,25145561,36
2,Florida,18801310,27
3,New York,19378102,27
4,Pennsylvania,12702379,18
5,Illinois,12830632,18
6,Georgia,9536504,14
7,North Carolina,9471653,13
8,Ohio,11486483,16
9,Michigan,9883640,14
10,New Jersey,8791894,12
11,Virginia,8001024,11
12,Washington,6724540,10
13,Arizona,6392017,9
14,Massachusetts,6547629,9
15,Tennessee,6346105,9
16,Indiana,6483802,9
17,Missouri,5988927,8
18,Maryland,5773552,8
19,Wisconsin,5686986,8
20,Colorado,5029196,7
21,Minnesota,5303925,8
22,South Carolina,4625364,7
23,Alabama,4779736,7
24,Louisiana,4533372,6
25,Kentucky,4339367,6
26,Oregon,3831074,5
27,Oklahoma,3751351,5
28,Connecticut,3574097,5
29,Utah,2763885,4
31,Iowa,3046355,4
32,Nevada,2700551,4
33,Arkansas,2915918,4
34,Mississippi,2967297,4
35,Kansas,2853118,4
36,New Mexico,2059179,3
37,Nebraska,1826341,3
38,West Virginia,1852994,3
39,Idaho,1567582,2
40,Hawaii,1360301,2
41,New Hampshire,1316470,2
42,Maine,1328361,2
43,Montana,989415,1
44,Rhode Island,1052567,2
45,Delaware,897934,1
46,South Dakota,814180,1
47,North Dakota,672591,1
48,Alaska,710231,1
50,Vermont,625741,1
51,Wyoming,563626,1

Reset Index to Avoid Confusion

In [8]:
representation_df = representation_df.reset_index(drop=True)

representation_df

,State,2010 Census Population,Total U.S. House of Representatives Seats
0,California,37253956,53
1,Texas,25145561,36
2,Florida,18801310,27
3,New York,19378102,27
4,Pennsylvania,12702379,18
5,Illinois,12830632,18
6,Georgia,9536504,14
7,North Carolina,9471653,13
8,Ohio,11486483,16
9,Michigan,9883640,14
10,New Jersey,8791894,12
11,Virginia,8001024,11
12,Washington,6724540,10
13,Arizona,6392017,9
14,Massachusetts,6547629,9
15,Tennessee,6346105,9
16,Indiana,6483802,9
17,Missouri,5988927,8
18,Maryland,5773552,8
19,Wisconsin,5686986,8
20,Colorado,5029196,7
21,Minnesota,5303925,8
22,South Carolina,4625364,7
23,Alabama,4779736,7
24,Louisiana,4533372,6
25,Kentucky,4339367,6
26,Oregon,3831074,5
27,Oklahoma,3751351,5
28,Connecticut,3574097,5
29,Utah,2763885,4
30,Iowa,3046355,4
31,Nevada,2700551,4
32,Arkansas,2915918,4
33,Mississippi,2967297,4
34,Kansas,2853118,4
35,New Mexico,2059179,3
36,Nebraska,1826341,3
37,West Virginia,1852994,3
38,Idaho,1567582,2
39,Hawaii,1360301,2
40,New Hampshire,1316470,2
41,Maine,1328361,2
42,Montana,989415,1
43,Rhode Island,1052567,2
44,Delaware,897934,1
45,South Dakota,814180,1
46,North Dakota,672591,1
47,Alaska,710231,1
48,Vermont,625741,1
49,Wyoming,563626,1

In [9]:
representation_df['Senate Seats'] = 2
electoral_college_col = representation_df['Total U.S. House of Representatives Seats'].astype(int) + 2
representation_df['Electoral College Votes'] = electoral_college_col
representation_df = representation_df.rename(columns = {'Total U.S. House of Representatives Seats': 'House of Reps Seats'})
representation_df

,State,2010 Census Population,House of Reps Seats,Senate Seats,Electoral College Votes
0,California,37253956,53,2,55
1,Texas,25145561,36,2,38
2,Florida,18801310,27,2,29
3,New York,19378102,27,2,29
4,Pennsylvania,12702379,18,2,20
5,Illinois,12830632,18,2,20
6,Georgia,9536504,14,2,16
7,North Carolina,9471653,13,2,15
8,Ohio,11486483,16,2,18
9,Michigan,9883640,14,2,16
10,New Jersey,8791894,12,2,14
11,Virginia,8001024,11,2,13
12,Washington,6724540,10,2,12
13,Arizona,6392017,9,2,11
14,Massachusetts,6547629,9,2,11
15,Tennessee,6346105,9,2,11
16,Indiana,6483802,9,2,11
17,Missouri,5988927,8,2,10
18,Maryland,5773552,8,2,10
19,Wisconsin,5686986,8,2,10
20,Colorado,5029196,7,2,9
21,Minnesota,5303925,8,2,10
22,South Carolina,4625364,7,2,9
23,Alabama,4779736,7,2,9
24,Louisiana,4533372,6,2,8
25,Kentucky,4339367,6,2,8
26,Oregon,3831074,5,2,7
27,Oklahoma,3751351,5,2,7
28,Connecticut,3574097,5,2,7
29,Utah,2763885,4,2,6
30,Iowa,3046355,4,2,6
31,Nevada,2700551,4,2,6
32,Arkansas,2915918,4,2,6
33,Mississippi,2967297,4,2,6
34,Kansas,2853118,4,2,6
35,New Mexico,2059179,3,2,5
36,Nebraska,1826341,3,2,5
37,West Virginia,1852994,3,2,5
38,Idaho,1567582,2,2,4
39,Hawaii,1360301,2,2,4
40,New Hampshire,1316470,2,2,4
41,Maine,1328361,2,2,4
42,Montana,989415,1,2,3
43,Rhode Island,1052567,2,2,4
44,Delaware,897934,1,2,3
45,South Dakota,814180,1,2,3
46,North Dakota,672591,1,2,3
47,Alaska,710231,1,2,3
48,Vermont,625741,1,2,3
49,Wyoming,563626,1,2,3