In [1]:
# Dependencies
import pandas as pd
from pandas import Series,DataFrame
import numpy as np
import pymongo
import time 
from IPython import get_ipython
import nbconvert

Read in Table from URL as Data Frame

In [2]:
rep_url = 'https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States_by_population'

df = pd.read_html(rep_url)[0]
df

      Rank                                              State  \
   Current  2010                                        State
0      1.0   1.0                                   California
1      2.0   2.0                                        Texas
2      3.0   4.0                                      Florida
3      4.0   3.0                                     New York
4      5.0   6.0                                 Pennsylvania
5      6.0   5.0                                     Illinois
6      7.0   7.0                                         Ohio
7      8.0   9.0                                      Georgia
8      9.0  10.0                               North Carolina
9     10.0   8.0                                     Michigan
10    11.0  11.0                                   New Jersey
11    12.0  12.0                                     Virginia
12    13.0  13.0                                   Washington
13    14.0  16.0                                      Arizona
14    15.0  14.0                                Massachusetts
15    16.0  17.0                                    Tennessee
16    17.0  15.0                                      Indiana
17    18.0  18.0                                     Missouri
18    19.0  19.0                                     Maryland
19    20.0  20.0                                    Wisconsin
20    21.0  22.0                                     Colorado
21    22.0  21.0                                    Minnesota
22    23.0  24.0                               South Carolina
23    24.0  23.0                                      Alabama
24    25.0  25.0                                    Louisiana
25    26.0  26.0                                     Kentucky
26    27.0  27.0                                       Oregon
27    28.0  28.0                                     Oklahoma
28    29.0  30.0                                  Connecticut
29    30.0  35.0                                         Utah
30    31.0  29.0                                  Puerto Rico
31    32.0  31.0                                         Iowa
32    33.0  36.0                                       Nevada
33    34.0  33.0                                     Arkansas
34    35.0  32.0                                  Mississippi
35    36.0  34.0                                       Kansas
36    37.0  37.0                                   New Mexico
37    38.0  39.0                                     Nebraska
38    39.0  38.0                                West Virginia
39    40.0  40.0                                        Idaho
40    41.0  41.0                                       Hawaii
41    42.0  43.0                                New Hampshire
42    43.0  42.0                                        Maine
43    44.0  45.0                                      Montana
44    45.0  44.0                                 Rhode Island
45    46.0  46.0                                     Delaware
46    47.0  47.0                                 South Dakota
47    48.0  49.0                                 North Dakota
48    49.0  48.0                                       Alaska
49    50.0  51.0                         District of Columbia
50    51.0  50.0                                      Vermont
51    52.0  52.0                                      Wyoming
52    53.0  53.0                                         Guam
53    54.0  54.0                          U.S. Virgin Islands
54    55.0  56.0                     Northern Mariana Islands
55    56.0  55.0                               American Samoa
56     NaN   NaN                     Contiguous United States
57     NaN   NaN                             The fifty states
58     NaN   NaN                          Fifty states + D.C.
59     NaN   NaN  Total U.S. (including D.C. and territories)

           Census population                  Change, 2010–2019               \
   Estimate, July 1, 2019[8] April 1, 2010[9]   Percent[note 3]     Absolute
0                   39512223         37253956              6.1%   +2,257,700
1                   28995881         25145561             15.3%   +3,850,320
2                   21477737         18801310             14.2%   +2,676,427
3                   19453561         19378102              0.4%      +75,459
4                   12801989         12702379              0.8%      +99,610
5                   12671821         12830632             –1.2%     –158,811
6                   11689100         11536504              1.3%     +152,596
7                   10617423          9687653              9.6%     +929,770
8                   10488084          9535483             10.0%     +952,601
9                    9986857          9883640             1.04%     +103,217
10                   8882190          8791894             1.03%      +90,296
11                   8535519          8001024              6.7%     +534,495
12                   7614893          6724540             13.2%     +890,353
13                   7278717          6392017             13.9%     +886,700
14                   6892503          6547629              5.3%     +344,874
15                   6829174          6346105              7.6%     +483,069
16                   6732219          6483802              3.8%     +248,417
17                   6137428          5988927             2.48%     +148,501
18                   6045680          5773552              4.7%     +272,128
19                   5822434          5686986              2.4%     +135,448
20                   5758736          5029196             14.5%     +729,540
21                   5639632          5303925              6.3%     +335,707
22                   5148714          4625364             11.3%     +523,350
23                   4903185          4779736              2.6%     +123,449
24                   4648794          4533372            2.546%     +115,422
25                   4467673          4339367             2.96%     +128,306
26                   4217737          3831074             10.1%     +386,663
27                   3956971          3751351              5.5%     +205,620
28                   3565287          3574097             –0.2%       –8,810
29                   3205958          2763885             16.0%     +442,073
30                   3193694          3725789            –14.3%     –532,095
31                   3155070          3046355              3.6%     +108,715
32                   3080156          2700551             14.1%     +379,605
33                   3017804          2915918              3.5%     +101,886
34                   2976149          2967297              0.3%       +8,852
35                   2913314          2853118              2.1%      +60,196
36                   2096829          2059179              1.8%      +37,650
37                   1934408          1826341              5.9%     +108,067
38                   1792147          1852994             –3.3%      –60,847
39                   1787065          1567582             14.0%     +219,483
40                   1415872          1360301              4.1%      +55,571
41                   1359711          1316470              3.3%      +43,241
42                   1344212          1328361              1.2%      +15,851
43                   1068778           989415              8.0%      +79,363
44                   1059361          1052567              0.6%       +6,794
45                    973764           897934              8.4%      +75,830
46                    884659           814180              8.7%      +70,479
47                    762062           672591             13.3%      +89,471
48                    731545           710231             3.00%      +21,314
49                    705749           601723             17.3%     +104,026
50                    623989           625741             –0.3%       –1,752
51                    578759           563626              2.7%      +15,133
52               168,485[10]      159,358[11]             5.73%       +9,127
53               106,235[12]      106,405[13]            –0.16%         –170
54                51,433[14]       53,883[15]            –4.55%       –2,450
55                49,437[16]       55,519[17]           –10.95%       –6,082
56                 325386357        306675006              6.2%  +19,011,351
57                 327533795        308143836              6.3%  +19,389,959
58                 328239523        308745538              6.3%  +19,493,985
59                 331808807        312846492              6.1%  +18,962,315

   Total U.S. House of Representatives Seats  \
   Total U.S. House of Representatives Seats
0                                         53
1                                         36
2                                         27
3                                         27
4                                         18
5                                         18
6                                         16
7                                         14
8                                         13
9                                         14
10                                        12
11                                        11
12                                        10
13                                         9
14                                         9
15                                         9
16                                         9
17                                         8
18                                         8
19                                         8
20                                         7
21                                         8
22                                         7
23                                         7
24                                         6
25                                         6
26                                         5
27                                         5
28                                         5
29                                         4
30                            1 (non-voting)
31                                         4
32                                         4
33                                         4
34                                         4
35                                         4
36                                         3
37                                         3
38                                         3
39                                         2
40                                         2
41                                         2
42                                         2
43                                         1
44                                         2
45                                         1
46                                         1
47                                         1
48                                         1
49                            1 (non-voting)
50                                         1
51                                         1
52                            1 (non-voting)
53                            1 (non-voting)
54                            1 (non-voting)
55                            1 (non-voting)
56                                       432
57                                       435
58                      435 (+ 1 non-voting)
59                      435 (+ 6 non-voting)

   Estimated population per electoral vote, 2019[note 1]  \
   Estimated population per electoral vote, 2019[note 1]
0                                              718404
1                                              763050
2                                              740611
3                                              670812
4                                              640099
5                                              633591
6                                              649394
7                                              663589
8                                              699206
9                                              624179
10                                             634442
11                                             656578
12                                             634574
13                                             661702
14                                             626591
15                                             620834
16                                             612020
17                                             613743
18                                             604568
19                                             582243
20                                             639860
21                                             563963
22                                             572079
23                                             544798
24                                             581099
25                                             558459
26                                             602534
27                                             565282
28                                             509327
29                                             534326
30                                                  —
31                                             525845
32                                             513359
33                                             502967
34                                             496024
35                                             485552
36                                             419366
37                                             386882
38                                             358435
39                                             446516
40                                             353968
41                                             339928
42                                             336053
43                                             356259
44                                             264840
45                                             324588
46                                             294886
47                                             254021
48                                             243848
49                                             235250
50                                             207996
51                                             192920
52                                                  —
53                                                  —
54                                                  —
55                                                  —
56                                             616262
57                                             612213
58                                             610111
59                                                  —

   Census population per House seat           \
                    Estimated, 2019     2010
0                            745514   702885
1                            805441   698503
2                            795472   696468
3                            720502   717707
4                            711222   705715
5                            703990   712864
6                            730569   721032
7                            758387   691975
8                            806776   733498
9                            713347   705974
10                           740183   732658
11                           775956   727366
12                           751489   672454
13                           808746   710224
14                           765834   727514
15                           758797   705123
16                           748024   720422
17                           767179   748615
18                           755710   721694
19                           727804   710873
20                           822677   720704
21                           704954   662991
22                           735531   660766
23                           700455   682819
24                           774799   755562
25                           744612   723228
26                           843547   766215
27                           791394   750270
28                           713057   714824
29                           801490   690972
30                          3193694  3725789
31                           788768   761717
32                           770039   675173
33                           754451   728990
34                           744037   742026
35                           728329   713280
36                           698943   686393
37                           644803   608780
38                           597391   617670
39                           893033   783826
40                           707936   680151
41                           679856   658233
42                           672106   664181
43                          1068778   989417
44                           529681   526466
45                           973764   897934
46                           884659   814180
47                           762062   672591
48                           731545   710231
49                                —        —
50                           623989   625741
51                           578759   563626
52                                —        —
53                                —        —
54                                —        —
55                                —        —
56                           753209   708285
57                           752951   708405
58                                —        —
59                                —        —

   Percent of the total U.S. population, 2019[note 2]
   Percent of the total U.S. population, 2019[note 2]
0                                              11.91%
1                                               8.74%
2                                               6.47%
3                                               5.86%
4                                               3.86%
5                                               3.82%
6                                               3.52%
7                                               3.20%
8                                               3.16%
9                                               3.01%
10                                              2.68%
11                                              2.57%
12                                              2.29%
13                                              2.19%
14                                              2.09%
15                                              2.06%
16                                              2.03%
17                                              1.85%
18                                              1.82%
19                                              1.75%
20                                              1.74%
21                                              1.70%
22                                              1.55%
23                                              1.48%
24                                              1.40%
25                                              1.35%
26                                              1.27%
27                                              1.19%
28                                              1.07%
29                                              0.97%
30                                              0.96%
31                                              0.95%
32                                              0.93%
33                                              0.91%
34                                              0.90%
35                                              0.88%
36                                              0.63%
37                                              0.58%
38                                              0.54%
39                                              0.54%
40                                              0.43%
41                                              0.41%

Flatten Multi-Level Index

In [3]:
df.columns = df.columns.get_level_values(0)

#df.columns = [' '.join(col).strip() for col in df.columns.values]

df

,Rank,Rank,State,Census population,Census population,"Change, 2010–2019","Change, 2010–2019",Total U.S. House of Representatives Seats,"Estimated population per electoral vote, 2019[note 1]",Census population per House seat,Census population per House seat,"Percent of the total U.S. population, 2019[note 2]"
0,1.0,1.0,California,39512223,37253956,6.1%,"+2,257,700",53,718404,745514,702885,11.91%
1,2.0,2.0,Texas,28995881,25145561,15.3%,"+3,850,320",36,763050,805441,698503,8.74%
2,3.0,4.0,Florida,21477737,18801310,14.2%,"+2,676,427",27,740611,795472,696468,6.47%
3,4.0,3.0,New York,19453561,19378102,0.4%,"+75,459",27,670812,720502,717707,5.86%
4,5.0,6.0,Pennsylvania,12801989,12702379,0.8%,"+99,610",18,640099,711222,705715,3.86%
5,6.0,5.0,Illinois,12671821,12830632,–1.2%,"–158,811",18,633591,703990,712864,3.82%
6,7.0,7.0,Ohio,11689100,11536504,1.3%,"+152,596",16,649394,730569,721032,3.52%
7,8.0,9.0,Georgia,10617423,9687653,9.6%,"+929,770",14,663589,758387,691975,3.20%
8,9.0,10.0,North Carolina,10488084,9535483,10.0%,"+952,601",13,699206,806776,733498,3.16%
9,10.0,8.0,Michigan,9986857,9883640,1.04%,"+103,217",14,624179,713347,705974,3.01%
10,11.0,11.0,New Jersey,8882190,8791894,1.03%,"+90,296",12,634442,740183,732658,2.68%
11,12.0,12.0,Virginia,8535519,8001024,6.7%,"+534,495",11,656578,775956,727366,2.57%
12,13.0,13.0,Washington,7614893,6724540,13.2%,"+890,353",10,634574,751489,672454,2.29%
13,14.0,16.0,Arizona,7278717,6392017,13.9%,"+886,700",9,661702,808746,710224,2.19%
14,15.0,14.0,Massachusetts,6892503,6547629,5.3%,"+344,874",9,626591,765834,727514,2.09%
15,16.0,17.0,Tennessee,6829174,6346105,7.6%,"+483,069",9,620834,758797,705123,2.06%
16,17.0,15.0,Indiana,6732219,6483802,3.8%,"+248,417",9,612020,748024,720422,2.03%
17,18.0,18.0,Missouri,6137428,5988927,2.48%,"+148,501",8,613743,767179,748615,1.85%
18,19.0,19.0,Maryland,6045680,5773552,4.7%,"+272,128",8,604568,755710,721694,1.82%
19,20.0,20.0,Wisconsin,5822434,5686986,2.4%,"+135,448",8,582243,727804,710873,1.75%
20,21.0,22.0,Colorado,5758736,5029196,14.5%,"+729,540",7,639860,822677,720704,1.74%
21,22.0,21.0,Minnesota,5639632,5303925,6.3%,"+335,707",8,563963,704954,662991,1.70%
22,23.0,24.0,South Carolina,5148714,4625364,11.3%,"+523,350",7,572079,735531,660766,1.55%
23,24.0,23.0,Alabama,4903185,4779736,2.6%,"+123,449",7,544798,700455,682819,1.48%
24,25.0,25.0,Louisiana,4648794,4533372,2.546%,"+115,422",6,581099,774799,755562,1.40%
25,26.0,26.0,Kentucky,4467673,4339367,2.96%,"+128,306",6,558459,744612,723228,1.35%
26,27.0,27.0,Oregon,4217737,3831074,10.1%,"+386,663",5,602534,843547,766215,1.27%
27,28.0,28.0,Oklahoma,3956971,3751351,5.5%,"+205,620",5,565282,791394,750270,1.19%
28,29.0,30.0,Connecticut,3565287,3574097,–0.2%,"–8,810",5,509327,713057,714824,1.07%
29,30.0,35.0,Utah,3205958,2763885,16.0%,"+442,073",4,534326,801490,690972,0.97%
30,31.0,29.0,Puerto Rico,3193694,3725789,–14.3%,"–532,095",1 (non-voting),—,3193694,3725789,0.96%
31,32.0,31.0,Iowa,3155070,3046355,3.6%,"+108,715",4,525845,788768,761717,0.95%
32,33.0,36.0,Nevada,3080156,2700551,14.1%,"+379,605",4,513359,770039,675173,0.93%
33,34.0,33.0,Arkansas,3017804,2915918,3.5%,"+101,886",4,502967,754451,728990,0.91%
34,35.0,32.0,Mississippi,2976149,2967297,0.3%,"+8,852",4,496024,744037,742026,0.90%
35,36.0,34.0,Kansas,2913314,2853118,2.1%,"+60,196",4,485552,728329,713280,0.88%
36,37.0,37.0,New Mexico,2096829,2059179,1.8%,"+37,650",3,419366,698943,686393,0.63%
37,38.0,39.0,Nebraska,1934408,1826341,5.9%,"+108,067",3,386882,644803,608780,0.58%
38,39.0,38.0,West Virginia,1792147,1852994,–3.3%,"–60,847",3,358435,597391,617670,0.54%
39,40.0,40.0,Idaho,1787065,1567582,14.0%,"+219,483",2,446516,893033,783826,0.54%
40,41.0,41.0,Hawaii,1415872,1360301,4.1%,"+55,571",2,353968,707936,680151,0.43%
41,42.0,43.0,New Hampshire,1359711,1316470,3.3%,"+43,241",2,339928,679856,658233,0.41%
42,43.0,42.0,Maine,1344212,1328361,1.2%,"+15,851",2,336053,672106,664181,0.41%
43,44.0,45.0,Montana,1068778,989415,8.0%,"+79,363",1,356259,1068778,989417,0.32%
44,45.0,44.0,Rhode Island,1059361,1052567,0.6%,"+6,794",2,264840,529681,526466,0.32%
45,46.0,46.0,Delaware,973764,897934,8.4%,"+75,830",1,324588,973764,897934,0.29%
46,47.0,47.0,South Dakota,884659,814180,8.7%,"+70,479",1,294886,884659,814180,0.27%
47,48.0,49.0,North Dakota,762062,672591,13.3%,"+89,471",1,254021,762062,672591,0.23%
48,49.0,48.0,Alaska,731545,710231,3.00%,"+21,314",1,243848,731545,710231,0.22%
49,50.0,51.0,District of Columbia,705749,601723,17.3%,"+104,026",1 (non-voting),235250,—,—,0.21%
50,51.0,50.0,Vermont,623989,625741,–0.3%,"–1,752",1,207996,623989,625741,0.19%
51,52.0,52.0,Wyoming,578759,563626,2.7%,"+15,133",1,192920,578759,563626,0.17%
52,53.0,53.0,Guam,"168,485[10]","159,358[11]",5.73%,"+9,127",1 (non-voting),—,—,—,0.05%
53,54.0,54.0,U.S. Virgin Islands,"106,235[12]","106,405[13]",–0.16%,–170,1 (non-voting),—,—,—,0.03%
54,55.0,56.0,Northern Mariana Islands,"51,433[14]","53,883[15]",–4.55%,"–2,450",1 (non-voting),—,—,—,0.02%
55,56.0,55.0,American Samoa,"49,437[16]","55,519[17]",–10.95%,"–6,082",1 (non-voting),—,—,—,0.02%
56,NaN,NaN,Contiguous United States,325386357,306675006,6.2%,"+19,011,351",432,616262,753209,708285,98.06%
57,NaN,NaN,The fifty states,327533795,308143836,6.3%,"+19,389,959",435,612213,752951,708405,98.71%
58,NaN,NaN,Fifty states + D.C.,328239523,308745538,6.3%,"+19,493,985",435 (+ 1 non-voting),610111,—,—,98.92%
59,NaN,NaN,Total U.S. (including D.C. and territories),331808807,312846492,6.1%,"+18,962,315",435 (+ 6 non-voting),—,—,—,100.00%

Select Relevant Columns

In [4]:
df = df[['State', 'Census population', 'Total U.S. House of Representatives Seats']]
df

,State,Census population,Census population,Total U.S. House of Representatives Seats
0,California,39512223,37253956,53
1,Texas,28995881,25145561,36
2,Florida,21477737,18801310,27
3,New York,19453561,19378102,27
4,Pennsylvania,12801989,12702379,18
5,Illinois,12671821,12830632,18
6,Ohio,11689100,11536504,16
7,Georgia,10617423,9687653,14
8,North Carolina,10488084,9535483,13
9,Michigan,9986857,9883640,14
10,New Jersey,8882190,8791894,12
11,Virginia,8535519,8001024,11
12,Washington,7614893,6724540,10
13,Arizona,7278717,6392017,9
14,Massachusetts,6892503,6547629,9
15,Tennessee,6829174,6346105,9
16,Indiana,6732219,6483802,9
17,Missouri,6137428,5988927,8
18,Maryland,6045680,5773552,8
19,Wisconsin,5822434,5686986,8
20,Colorado,5758736,5029196,7
21,Minnesota,5639632,5303925,8
22,South Carolina,5148714,4625364,7
23,Alabama,4903185,4779736,7
24,Louisiana,4648794,4533372,6
25,Kentucky,4467673,4339367,6
26,Oregon,4217737,3831074,5
27,Oklahoma,3956971,3751351,5
28,Connecticut,3565287,3574097,5
29,Utah,3205958,2763885,4
30,Puerto Rico,3193694,3725789,1 (non-voting)
31,Iowa,3155070,3046355,4
32,Nevada,3080156,2700551,4
33,Arkansas,3017804,2915918,4
34,Mississippi,2976149,2967297,4
35,Kansas,2913314,2853118,4
36,New Mexico,2096829,2059179,3
37,Nebraska,1934408,1826341,3
38,West Virginia,1792147,1852994,3
39,Idaho,1787065,1567582,2
40,Hawaii,1415872,1360301,2
41,New Hampshire,1359711,1316470,2
42,Maine,1344212,1328361,2
43,Montana,1068778,989415,1
44,Rhode Island,1059361,1052567,2
45,Delaware,973764,897934,1
46,South Dakota,884659,814180,1
47,North Dakota,762062,672591,1
48,Alaska,731545,710231,1
49,District of Columbia,705749,601723,1 (non-voting)
50,Vermont,623989,625741,1
51,Wyoming,578759,563626,1
52,Guam,"168,485[10]","159,358[11]",1 (non-voting)
53,U.S. Virgin Islands,"106,235[12]","106,405[13]",1 (non-voting)
54,Northern Mariana Islands,"51,433[14]","53,883[15]",1 (non-voting)
55,American Samoa,"49,437[16]","55,519[17]",1 (non-voting)
56,Contiguous United States,325386357,306675006,432
57,The fifty states,327533795,308143836,435
58,Fifty states + D.C.,328239523,308745538,435 (+ 1 non-voting)
59,Total U.S. (including D.C. and territories),331808807,312846492,435 (+ 6 non-voting)

Rename 2010 Census Column to Address Duplicate Column Names

In [5]:
column_names = df.columns.values
column_names[2] = "2010 Census Population"
df.columns = column_names
df

,State,Census population,2010 Census Population,Total U.S. House of Representatives Seats
0,California,39512223,37253956,53
1,Texas,28995881,25145561,36
2,Florida,21477737,18801310,27
3,New York,19453561,19378102,27
4,Pennsylvania,12801989,12702379,18
5,Illinois,12671821,12830632,18
6,Ohio,11689100,11536504,16
7,Georgia,10617423,9687653,14
8,North Carolina,10488084,9535483,13
9,Michigan,9986857,9883640,14
10,New Jersey,8882190,8791894,12
11,Virginia,8535519,8001024,11
12,Washington,7614893,6724540,10
13,Arizona,7278717,6392017,9
14,Massachusetts,6892503,6547629,9
15,Tennessee,6829174,6346105,9
16,Indiana,6732219,6483802,9
17,Missouri,6137428,5988927,8
18,Maryland,6045680,5773552,8
19,Wisconsin,5822434,5686986,8
20,Colorado,5758736,5029196,7
21,Minnesota,5639632,5303925,8
22,South Carolina,5148714,4625364,7
23,Alabama,4903185,4779736,7
24,Louisiana,4648794,4533372,6
25,Kentucky,4467673,4339367,6
26,Oregon,4217737,3831074,5
27,Oklahoma,3956971,3751351,5
28,Connecticut,3565287,3574097,5
29,Utah,3205958,2763885,4
30,Puerto Rico,3193694,3725789,1 (non-voting)
31,Iowa,3155070,3046355,4
32,Nevada,3080156,2700551,4
33,Arkansas,3017804,2915918,4
34,Mississippi,2976149,2967297,4
35,Kansas,2913314,2853118,4
36,New Mexico,2096829,2059179,3
37,Nebraska,1934408,1826341,3
38,West Virginia,1792147,1852994,3
39,Idaho,1787065,1567582,2
40,Hawaii,1415872,1360301,2
41,New Hampshire,1359711,1316470,2
42,Maine,1344212,1328361,2
43,Montana,1068778,989415,1
44,Rhode Island,1059361,1052567,2
45,Delaware,973764,897934,1
46,South Dakota,884659,814180,1
47,North Dakota,762062,672591,1
48,Alaska,731545,710231,1
49,District of Columbia,705749,601723,1 (non-voting)
50,Vermont,623989,625741,1
51,Wyoming,578759,563626,1
52,Guam,"168,485[10]","159,358[11]",1 (non-voting)
53,U.S. Virgin Islands,"106,235[12]","106,405[13]",1 (non-voting)
54,Northern Mariana Islands,"51,433[14]","53,883[15]",1 (non-voting)
55,American Samoa,"49,437[16]","55,519[17]",1 (non-voting)
56,Contiguous United States,325386357,306675006,432
57,The fifty states,327533795,308143836,435
58,Fifty states + D.C.,328239523,308745538,435 (+ 1 non-voting)
59,Total U.S. (including D.C. and territories),331808807,312846492,435 (+ 6 non-voting)

Drop Estimated Unnecessary Estimated Population Column

In [6]:
df = df.drop(df.columns[1], axis=1)
df

,State,2010 Census Population,Total U.S. House of Representatives Seats
0,California,37253956,53
1,Texas,25145561,36
2,Florida,18801310,27
3,New York,19378102,27
4,Pennsylvania,12702379,18
5,Illinois,12830632,18
6,Ohio,11536504,16
7,Georgia,9687653,14
8,North Carolina,9535483,13
9,Michigan,9883640,14
10,New Jersey,8791894,12
11,Virginia,8001024,11
12,Washington,6724540,10
13,Arizona,6392017,9
14,Massachusetts,6547629,9
15,Tennessee,6346105,9
16,Indiana,6483802,9
17,Missouri,5988927,8
18,Maryland,5773552,8
19,Wisconsin,5686986,8
20,Colorado,5029196,7
21,Minnesota,5303925,8
22,South Carolina,4625364,7
23,Alabama,4779736,7
24,Louisiana,4533372,6
25,Kentucky,4339367,6
26,Oregon,3831074,5
27,Oklahoma,3751351,5
28,Connecticut,3574097,5
29,Utah,2763885,4
30,Puerto Rico,3725789,1 (non-voting)
31,Iowa,3046355,4
32,Nevada,2700551,4
33,Arkansas,2915918,4
34,Mississippi,2967297,4
35,Kansas,2853118,4
36,New Mexico,2059179,3
37,Nebraska,1826341,3
38,West Virginia,1852994,3
39,Idaho,1567582,2
40,Hawaii,1360301,2
41,New Hampshire,1316470,2
42,Maine,1328361,2
43,Montana,989415,1
44,Rhode Island,1052567,2
45,Delaware,897934,1
46,South Dakota,814180,1
47,North Dakota,672591,1
48,Alaska,710231,1
49,District of Columbia,601723,1 (non-voting)
50,Vermont,625741,1
51,Wyoming,563626,1
52,Guam,"159,358[11]",1 (non-voting)
53,U.S. Virgin Islands,"106,405[13]",1 (non-voting)
54,Northern Mariana Islands,"53,883[15]",1 (non-voting)
55,American Samoa,"55,519[17]",1 (non-voting)
56,Contiguous United States,306675006,432
57,The fifty states,308143836,435
58,Fifty states + D.C.,308745538,435 (+ 1 non-voting)
59,Total U.S. (including D.C. and territories),312846492,435 (+ 6 non-voting)

Replace Values for House of Representatives Seats w/ NaN for non-State Rows and Drop NaNs

In [7]:
representation_df = df.replace({'1 (non-voting)': np.NaN, '435 (+ 1 non-voting)': np.NaN, '435 (+ 6 non-voting)': np.NaN, 
                         '432': np.NaN, '435': np.NaN})

representation_df = representation_df.dropna()
representation_df

,State,2010 Census Population,Total U.S. House of Representatives Seats
0,California,37253956,53
1,Texas,25145561,36
2,Florida,18801310,27
3,New York,19378102,27
4,Pennsylvania,12702379,18
5,Illinois,12830632,18
6,Ohio,11536504,16
7,Georgia,9687653,14
8,North Carolina,9535483,13
9,Michigan,9883640,14
10,New Jersey,8791894,12
11,Virginia,8001024,11
12,Washington,6724540,10
13,Arizona,6392017,9
14,Massachusetts,6547629,9
15,Tennessee,6346105,9
16,Indiana,6483802,9
17,Missouri,5988927,8
18,Maryland,5773552,8
19,Wisconsin,5686986,8
20,Colorado,5029196,7
21,Minnesota,5303925,8
22,South Carolina,4625364,7
23,Alabama,4779736,7
24,Louisiana,4533372,6
25,Kentucky,4339367,6
26,Oregon,3831074,5
27,Oklahoma,3751351,5
28,Connecticut,3574097,5
29,Utah,2763885,4
31,Iowa,3046355,4
32,Nevada,2700551,4
33,Arkansas,2915918,4
34,Mississippi,2967297,4
35,Kansas,2853118,4
36,New Mexico,2059179,3
37,Nebraska,1826341,3
38,West Virginia,1852994,3
39,Idaho,1567582,2
40,Hawaii,1360301,2
41,New Hampshire,1316470,2
42,Maine,1328361,2
43,Montana,989415,1
44,Rhode Island,1052567,2
45,Delaware,897934,1
46,South Dakota,814180,1
47,North Dakota,672591,1
48,Alaska,710231,1
50,Vermont,625741,1
51,Wyoming,563626,1

Reset Index to Avoid Confusion

In [8]:
representation_df = representation_df.reset_index(drop=True)

representation_df

,State,2010 Census Population,Total U.S. House of Representatives Seats
0,California,37253956,53
1,Texas,25145561,36
2,Florida,18801310,27
3,New York,19378102,27
4,Pennsylvania,12702379,18
5,Illinois,12830632,18
6,Ohio,11536504,16
7,Georgia,9687653,14
8,North Carolina,9535483,13
9,Michigan,9883640,14
10,New Jersey,8791894,12
11,Virginia,8001024,11
12,Washington,6724540,10
13,Arizona,6392017,9
14,Massachusetts,6547629,9
15,Tennessee,6346105,9
16,Indiana,6483802,9
17,Missouri,5988927,8
18,Maryland,5773552,8
19,Wisconsin,5686986,8
20,Colorado,5029196,7
21,Minnesota,5303925,8
22,South Carolina,4625364,7
23,Alabama,4779736,7
24,Louisiana,4533372,6
25,Kentucky,4339367,6
26,Oregon,3831074,5
27,Oklahoma,3751351,5
28,Connecticut,3574097,5
29,Utah,2763885,4
30,Iowa,3046355,4
31,Nevada,2700551,4
32,Arkansas,2915918,4
33,Mississippi,2967297,4
34,Kansas,2853118,4
35,New Mexico,2059179,3
36,Nebraska,1826341,3
37,West Virginia,1852994,3
38,Idaho,1567582,2
39,Hawaii,1360301,2
40,New Hampshire,1316470,2
41,Maine,1328361,2
42,Montana,989415,1
43,Rhode Island,1052567,2
44,Delaware,897934,1
45,South Dakota,814180,1
46,North Dakota,672591,1
47,Alaska,710231,1
48,Vermont,625741,1
49,Wyoming,563626,1

In [9]:
representation_df['senate_seats'] = 2
electoral_college_col = representation_df['Total U.S. House of Representatives Seats'].astype(int) + 2
representation_df['electoral_college_votes'] = electoral_college_col
representation_df = representation_df.rename(columns = {'2010 Census Population': '2010_census_population',
                                                        'Total U.S. House of Representatives Seats': 'house_of_reps_seats'
                                                       })
representation_df['pop/senator'] = representation_df['2010_census_population'].astype(int) / representation_df['senate_seats'] / 1000000
representation_df['pop/rep'] = representation_df['2010_census_population'].astype(int) / representation_df['house_of_reps_seats'].astype(int) / 1000000
representation_df['pop/elector'] = representation_df['2010_census_population'].astype(int) / representation_df['electoral_college_votes'].astype(int) / 1000000
representation_df

,State,2010_census_population,house_of_reps_seats,senate_seats,electoral_college_votes,pop/senator,pop/rep,pop/elector
0,California,37253956,53,2,55,18.626978,0.702905,0.677345
1,Texas,25145561,36,2,38,12.572781,0.698488,0.661725
2,Florida,18801310,27,2,29,9.400655,0.696345,0.648321
3,New York,19378102,27,2,29,9.689051,0.717707,0.668210
4,Pennsylvania,12702379,18,2,20,6.351190,0.705688,0.635119
5,Illinois,12830632,18,2,20,6.415316,0.712813,0.641532
6,Ohio,11536504,16,2,18,5.768252,0.721032,0.640917
7,Georgia,9687653,14,2,16,4.843826,0.691975,0.605478
8,North Carolina,9535483,13,2,15,4.767741,0.733499,0.635699
9,Michigan,9883640,14,2,16,4.941820,0.705974,0.617727
10,New Jersey,8791894,12,2,14,4.395947,0.732658,0.627992
11,Virginia,8001024,11,2,13,4.000512,0.727366,0.615463
12,Washington,6724540,10,2,12,3.362270,0.672454,0.560378
13,Arizona,6392017,9,2,11,3.196009,0.710224,0.581092
14,Massachusetts,6547629,9,2,11,3.273814,0.727514,0.595239
15,Tennessee,6346105,9,2,11,3.173052,0.705123,0.576919
16,Indiana,6483802,9,2,11,3.241901,0.720422,0.589437
17,Missouri,5988927,8,2,10,2.994464,0.748616,0.598893
18,Maryland,5773552,8,2,10,2.886776,0.721694,0.577355
19,Wisconsin,5686986,8,2,10,2.843493,0.710873,0.568699
20,Colorado,5029196,7,2,9,2.514598,0.718457,0.558800
21,Minnesota,5303925,8,2,10,2.651962,0.662991,0.530393
22,South Carolina,4625364,7,2,9,2.312682,0.660766,0.513929
23,Alabama,4779736,7,2,9,2.389868,0.682819,0.531082
24,Louisiana,4533372,6,2,8,2.266686,0.755562,0.566671
25,Kentucky,4339367,6,2,8,2.169684,0.723228,0.542421
26,Oregon,3831074,5,2,7,1.915537,0.766215,0.547296
27,Oklahoma,3751351,5,2,7,1.875676,0.750270,0.535907
28,Connecticut,3574097,5,2,7,1.787049,0.714819,0.510585
29,Utah,2763885,4,2,6,1.381943,0.690971,0.460647
30,Iowa,3046355,4,2,6,1.523178,0.761589,0.507726
31,Nevada,2700551,4,2,6,1.350275,0.675138,0.450092
32,Arkansas,2915918,4,2,6,1.457959,0.728980,0.485986
33,Mississippi,2967297,4,2,6,1.483648,0.741824,0.494549
34,Kansas,2853118,4,2,6,1.426559,0.713279,0.475520
35,New Mexico,2059179,3,2,5,1.029589,0.686393,0.411836
36,Nebraska,1826341,3,2,5,0.913170,0.608780,0.365268
37,West Virginia,1852994,3,2,5,0.926497,0.617665,0.370599
38,Idaho,1567582,2,2,4,0.783791,0.783791,0.391896
39,Hawaii,1360301,2,2,4,0.680150,0.680150,0.340075
40,New Hampshire,1316470,2,2,4,0.658235,0.658235,0.329118
41,Maine,1328361,2,2,4,0.664180,0.664180,0.332090
42,Montana,989415,1,2,3,0.494708,0.989415,0.329805
43,Rhode Island,1052567,2,2,4,0.526284,0.526284,0.263142
44,Delaware,897934,1,2,3,0.448967,0.897934,0.299311
45,South Dakota,814180,1,2,3,0.407090,0.814180,0.271393
46,North Dakota,672591,1,2,3,0.336296,0.672591,0.224197
47,Alaska,710231,1,2,3,0.355115,0.710231,0.236744
48,Vermont,625741,1,2,3,0.312870,0.625741,0.208580
49,Wyoming,563626,1,2,3,0.281813,0.563626,0.187875

Read in Federal Funding CSV (Soure: https://worldpopulationreview.com/state-rankings/federal-aid-by-state)

In [10]:
funding_df = pd.read_csv('federal-aid-by-state.csv')
funding_df

,State,federalFunding,totalFederalFunding,benefitsRecipients,medianHouseholdIncome
0,Virginia,10301,1.768000e+11,8.1,71535
1,Kentucky,9145,7.080000e+10,14.1,48375
2,New Mexico,8692,3.170000e+10,17.4,46744
3,West Virginia,7283,2.460000e+10,16.8,43469
4,Alaska,7048,1.300000e+10,10.8,73181
5,Mississippi,6880,3.780000e+10,15.3,43529
6,Alabama,6694,6.580000e+10,14.0,48123
7,Maryland,6035,1.051000e+11,10.3,80776
8,Maine,5572,1.740000e+10,12.8,56277
9,Hawaii,5270,1.990000e+10,10.7,77765
10,Arkansas,5080,3.510000e+10,11.8,45869
11,South Carolina,5008,5.970000e+10,12.3,50570
12,Arizona,4430,8.280000e+10,10.8,56581
13,Oklahoma,3986,4.510000e+10,13.2,50051
14,Missouri,3949,7.230000e+10,11.0,53578
15,Montana,3808,1.220000e+10,9.4,53386
16,Louisiana,3785,5.200000e+10,16.4,46145
17,Vermont,3741,8.000000e+09,11.5,57513
18,Tennessee,3591,7.630000e+10,13.5,51340
19,Idaho,3428,1.750000e+10,9.7,52225
20,North Carolina,3358,1.131000e+11,12.3,52752
21,Delaware,2892,1.150000e+10,10.4,62852
22,Ohio,2750,1.257000e+11,13.2,54021
23,Oregon,2477,4.570000e+10,15.4,60212
24,Michigan,2474,1.084000e+11,13.1,54909
25,Indiana,2359,6.780000e+10,9.3,54181
26,Pennsylvania,2299,1.558000e+11,12.9,59195
27,Georgia,2253,1.045000e+11,12.6,56183
28,Rhode Island,2228,1.260000e+10,15.4,63870
29,Florida,2187,2.377000e+11,13.6,52594
30,Kansas,1983,3.130000e+10,7.7,56422
31,South Dakota,1409,9.300000e+09,8.9,56521
32,Nevada,1140,2.870000e+10,12.2,58003
33,Iowa,1105,2.990000e+10,9.6,58570
34,Minnesota,959,6.440000e+10,7.8,68388
35,Wyoming,670,7.100000e+09,6.3,60434
36,Wisconsin,536,5.540000e+10,10.6,59305
37,Texas,304,2.690000e+11,12.0,59206
38,Utah,296,2.390000e+10,6.8,68358
39,California,12,4.361000e+11,8.9,71805
40,Colorado,-95,5.750000e+10,7.6,69117
41,Nebraska,-164,1.770000e+10,8.3,59970
42,Washington,-184,8.050000e+10,12.3,70979
43,New Hampshire,-234,1.500000e+10,7.0,73381
44,Illinois,-364,1.318000e+11,12.9,62992
45,North Dakota,-720,7.900000e+09,6.3,61843
46,New York,-1792,2.206000e+11,14.8,64894
47,Massachusetts,-2343,7.870000e+10,11.7,77385
48,New Jersey,-2368,9.770000e+10,8.9,80088
49,Connecticut,-4000,4.110000e+10,12.0,74168

In [11]:
funding_df = funding_df.rename(columns = {'State':'state','federalFunding': 'per_capita_fed_funding', 
                                         'totalFederalFunding': 'total_fed_funding_billions', 
                                         'benefitsRecipients': 'benefits_receipients_percent',
                                        'medianHouseholdIncome': 'median_household_income_billions'})

funding_df['total_fed_funding_billions'] = funding_df['total_fed_funding_billions'] / 1000000000

funding_df

,state,per_capita_fed_funding,total_fed_funding_billions,benefits_receipients_percent,median_household_income_billions
0,Virginia,10301,176.8,8.1,71535
1,Kentucky,9145,70.8,14.1,48375
2,New Mexico,8692,31.7,17.4,46744
3,West Virginia,7283,24.6,16.8,43469
4,Alaska,7048,13.0,10.8,73181
5,Mississippi,6880,37.8,15.3,43529
6,Alabama,6694,65.8,14.0,48123
7,Maryland,6035,105.1,10.3,80776
8,Maine,5572,17.4,12.8,56277
9,Hawaii,5270,19.9,10.7,77765
10,Arkansas,5080,35.1,11.8,45869
11,South Carolina,5008,59.7,12.3,50570
12,Arizona,4430,82.8,10.8,56581
13,Oklahoma,3986,45.1,13.2,50051
14,Missouri,3949,72.3,11.0,53578
15,Montana,3808,12.2,9.4,53386
16,Louisiana,3785,52.0,16.4,46145
17,Vermont,3741,8.0,11.5,57513
18,Tennessee,3591,76.3,13.5,51340
19,Idaho,3428,17.5,9.7,52225
20,North Carolina,3358,113.1,12.3,52752
21,Delaware,2892,11.5,10.4,62852
22,Ohio,2750,125.7,13.2,54021
23,Oregon,2477,45.7,15.4,60212
24,Michigan,2474,108.4,13.1,54909
25,Indiana,2359,67.8,9.3,54181
26,Pennsylvania,2299,155.8,12.9,59195
27,Georgia,2253,104.5,12.6,56183
28,Rhode Island,2228,12.6,15.4,63870
29,Florida,2187,237.7,13.6,52594
30,Kansas,1983,31.3,7.7,56422
31,South Dakota,1409,9.3,8.9,56521
32,Nevada,1140,28.7,12.2,58003
33,Iowa,1105,29.9,9.6,58570
34,Minnesota,959,64.4,7.8,68388
35,Wyoming,670,7.1,6.3,60434
36,Wisconsin,536,55.4,10.6,59305
37,Texas,304,269.0,12.0,59206
38,Utah,296,23.9,6.8,68358
39,California,12,436.1,8.9,71805
40,Colorado,-95,57.5,7.6,69117
41,Nebraska,-164,17.7,8.3,59970
42,Washington,-184,80.5,12.3,70979
43,New Hampshire,-234,15.0,7.0,73381
44,Illinois,-364,131.8,12.9,62992
45,North Dakota,-720,7.9,6.3,61843
46,New York,-1792,220.6,14.8,64894
47,Massachusetts,-2343,78.7,11.7,77385
48,New Jersey,-2368,97.7,8.9,80088
49,Connecticut,-4000,41.1,12.0,74168

In [12]:
elect_url = 'https://en.wikipedia.org/wiki/List_of_United_States_Senate_election_results_by_state'

elect_df = pd.read_html(elect_url)[2]

elect_df

   Unnamed: 0_level_0  First Party System                      \
                State            DR votes             F votes
0             Alabama                   3                   0
1              Alaska                 NaN                 NaN
2             Arizona                 NaN                 NaN
3            Arkansas                 NaN                 NaN
4          California                 NaN                 NaN
5            Colorado                 NaN                 NaN
6         Connecticut                   2                   8
7            Delaware                   0                  10
8             Florida                 NaN                 NaN
9             Georgia                   9                   1
10             Hawaii                 NaN                 NaN
11              Idaho                 NaN                 NaN
12           Illinois                   3                   0
13            Indiana                   4                   0
14               Iowa                 NaN                 NaN
15             Kansas                 NaN                 NaN
16           Kentucky                   9                   1
17          Louisiana                   5                   0
18              Maine                   3                   0
19           Maryland                   6                   4
20      Massachusetts                   1                   9
21           Michigan                 NaN                 NaN
22          Minnesota                 NaN                 NaN
23        Mississippi                   4                   0
24           Missouri                   2                   0
25            Montana                 NaN                 NaN
26           Nebraska                 NaN                 NaN
27             Nevada                 NaN                 NaN
28      New Hampshire                   7                   3
29         New Jersey                   8                   2
30         New Mexico                 NaN                 NaN
31           New York                   6                   4
32     North Carolina                  10                   0
33       North Dakota                 NaN                 NaN
34               Ohio                   8                   0
35           Oklahoma                 NaN                 NaN
36             Oregon                 NaN                 NaN
37       Pennsylvania                   8                   2
38       Rhode Island                   5                   5
39     South Carolina                   9                   1
40       South Dakota                 NaN                 NaN
41          Tennessee                  11                   0
42              Texas                 NaN                 NaN
43               Utah                 NaN                 NaN
44            Vermont                   6                   4
45           Virginia                  10                   0
46         Washington                 NaN                 NaN
47      West Virginia                 NaN                 NaN
48          Wisconsin                 NaN                 NaN
49            Wyoming                 NaN                 NaN
50          Northeast                  46                  37
51              South                  76                  17
52            Midwest                  17                   0
53               West                 NaN                 NaN
54      United States                 139                  54
55              State            DR votes             F votes
56                NaN  First Party System  First Party System

                        Second Party System                       \
                  % DR              D votes           AJ/W votes
0                  100                   10                    0
1                  NaN                  NaN                  NaN
2                  NaN                  NaN                  NaN
3                  NaN                    8                    0
4                  NaN                    3                    0
5                  NaN                  NaN                  NaN
6                   20                    3                    5
7                    0                    1                    8
8                  NaN                    4                    1
9                   90                    7                    3
10                 NaN                  NaN                  NaN
11                 NaN                  NaN                  NaN
12                 100                   10                    0
13                 100                    6                    3
14                 NaN                    3                    0
15                 NaN                  NaN                  NaN
16                  90                    1                    9
17                 100                    7                    3
18                 100                    6                    3
19                  60                    0                    9
20                  10                    0                    8
21                 NaN                    6                    1
22                 NaN                  NaN                  NaN
23                 100                    7                    2
24                 100                    8                    1
25                 NaN                  NaN                  NaN
26                 NaN                  NaN                  NaN
27                 NaN                  NaN                  NaN
28                  70                    7                    1
29                  80                    3                    6
30                 NaN                  NaN                  NaN
31                  60                    5                    3
32                 100                    7                    3
33                 NaN                  NaN                  NaN
34                 100                    5                    3
35                 NaN                  NaN                  NaN
36                 NaN                  NaN                  NaN
37                  80                    8                    1
38                  50                    2                    7
39                  90                    7                    1
40                 NaN                  NaN                  NaN
41                 100                    4                    5
42                 NaN                    4                    0
43                 NaN                  NaN                  NaN
44                  60                    0                    9
45                 100                    5                    4
46                 NaN                  NaN                  NaN
47                 NaN                  NaN                  NaN
48                 NaN                    3                    0
49                 NaN                  NaN                  NaN
50                  55                   34                   43
51                  82                   72                   48
52                 100                   41                    8
53                 NaN                    3                    0
54                  72                  150                   95
55                % DR              D votes           AJ/W votes
56  First Party System  Second Party System  Second Party System

                                              Third Party System  \
            Other votes                  % D             D votes
0                     0                  100                   9
1                   NaN                  NaN                 NaN
2                   NaN                  NaN                 NaN
3                     0                  100                   9
4                     0                  100                   6
5                   NaN                  NaN                   0
6                     1                   33                   1
7                     0                   11                  13
8                     0                   80                   8
9                     0                   70                  10
10                  NaN                  NaN                 NaN
11                  NaN                  NaN                   0
12                    0                  100                   2
13                    0                   67                   8
14                    1                   75                   0
15                  NaN                  NaN                   0
16                    0                   10                  13
17                    0                   70                   8
18                    0                   66                   1
19                    0                    0                  11
20                    1                    0                   0
21                    0                   86                   0
22                  NaN                  NaN                   1
23                    0                   78                   9
24                    0                   89                  10
25                  NaN                  NaN                   0
26                  NaN                  NaN                   0
27                  NaN                  NaN                   1
28                    2                   70                   0
29                    0                   33                  10
30                  NaN                  NaN                 NaN
31                    1                   63                   3
32                    0                   70                  10
33                  NaN                  NaN                   1
34                    1                   56                   5
35                  NaN                  NaN                 NaN
36                  NaN                  NaN                   5
37                    0                   89                   2
38                    0                   22                   0
39                    2                   70                   8
40                  NaN                  NaN                   0
41                    0                   44                  12
42                    0                  100                  10
43                  NaN                  NaN                 NaN
44                    0                    0                   0
45                    0                   56                   9
46                  NaN                  NaN                   0
47                  NaN                  NaN                   8
48                    1                   75                   2
49                  NaN                  NaN                   0
50                    5                   41                  17
51                    2                   59                 147
52                    3                   79                  29
53                    0                  100                  12
54                   10                   59                 205
55          Other votes                  % D             D votes
56  Second Party System  Second Party System  Third Party System

                        ...  Fifth Party System                      \
               R votes  ...         Other votes                 % D
0                    3  ...                   0                 100
1                  NaN  ...                   0                 100
2                  NaN  ...                   0                  75
3                    4  ...                   0                 100
4                    6  ...                   0                  33
5                    7  ...                   0                  50
6                   11  ...                   0                  67
7                    1  ...                   0                  33
8                    3  ...                   0                 100
9                    1  ...                   0                 100
10                 NaN  ...                   0                  40
11                   3  ...                   0                  50
12                  10  ...                   0                  58
13                   5  ...                   0                  50
14                  13  ...                   0                  33
15                  12  ...                   0                   8
16                   0  ...                   0                  67
17                   4  ...                   0                 100
18                  13  ...                   0                  17
19                   0  ...                   0                  67
20                  14  ...                   0                  42
21                  14  ...                   0                  42
22                  13  ...                   2                  50
23                   3  ...                   0                 100
24                   2  ...                   0                  83
25                   4  ...                   0                  92
26                  11  ...                   1                   8
27                  10  ...                   0                  83
28                  13  ...                   0                  17
29                   4  ...                   0                  33
30                 NaN  ...                   0                  92
31                  10  ...                   0                  58
32                   2  ...                   0                 100
33                   3  ...                   0                  17
34                   8  ...                   0                  50
35                 NaN  ...                   0                  92
36                   9  ...                   0                  33
37                  11  ...                   0                  42
38                  14  ...                   0                 100
39                   4  ...                   0                  92
40                   3  ...                   0                  17
41                   2  ...                   0                  92
42                   2  ...                   0                  92
43                 NaN  ...                   0                  58
44                  13  ...                   0                   0
45                   1  ...                   0                 100
46                   4  ...                   0                  92
47                   3  ...                   0                  92
48                  11  ...                   1                  33
49                   4  ...                   0                  67
50                 103  ...                   0                  42
51                  33  ...                   0                  89
52                  94  ...                   4                  40
53                  47  ...                   0                  66
54                 277  ...                   4                  63
55             R votes  ...         Other votes                 % D
56  Third Party System  ...  Fifth Party System  Fifth Party System

    Sixth Party System                                          \
               D votes             R votes         Other votes
0                    8                   8                   0
1                    3                  13                   0
2                    3                  13                   0
3                   13                   3                   0
4                   13                   3                   0
5                    7                   9                   0
6                   13                   3                   0
7                   11                   5                   0
8                   10                   6                   0
9                    8                   8                   0
10                  15                   1                   0
11                   2                  14                   0
12                  11                   5                   0
13                   6                  10                   0
14                   8                   8                   0
15                   0                  16                   0
16                   6                  10                   0
17                  13                   3                   0
18                   5                  10                   1
19                  12                   4                   0
20                  15                   1                   0
21                  14                   2                   0
22                  10                   6                   0
23                   4                  12                   0
24                   6                  10                   0
25                  12                   4                   0
26                  10                   6                   0
27                  10                   6                   0
28                   4                  12                   0
29                  15                   1                   0
30                   9                   7                   0
31                  10                   5                   1
32                   5                  11                   0
33                  12                   4                   0
34                   9                   7                   0
35                   3                  13                   0
36                   5                  11                   0
37                   2                  14                   0
38                  11                   5                   0
39                   6                  10                   0
40                   9                   7                   0
41                   5                  11                   0
42                   4                  12                   0
43                   1                  15                   0
44                   7                   7                   2
45                   6                   8                   2
46                  13                   3                   0
47                  15                   1                   0
48                  13                   3                   0
49                   1                  15                   0
50                  82                  56                   4
51                 129                 123                   2
52                 108                  85                   0
53                  94                 114                   0
54                 412                 378                   7
55             D votes             R votes         Other votes
56  Sixth Party System  Sixth Party System  Sixth Party System

                        Overall since 1828                      \
                   % D             D votes             R votes
0                   50                  51                  11
1                   19                   8                  13
2                   19                  19                  17
3                   81                  54                   7
4                   81                  27                  28
5                   44                  20                  27
6                   81                  24                  31
7                   69                  32                  31
8                   63                  46                   9
9                   50                  49                   9
10                  94                  17                   4
11                  13                   8                  33

In [13]:
elect_df = elect_df.head(50)
#elect_df.drop(elect_df.index([[50, 57]])
#elect_df.index
elect_df

   Unnamed: 0_level_0 First Party System              Second Party System  \
                State           DR votes F votes % DR             D votes
0             Alabama                  3       0  100                  10
1              Alaska                NaN     NaN  NaN                 NaN
2             Arizona                NaN     NaN  NaN                 NaN
3            Arkansas                NaN     NaN  NaN                   8
4          California                NaN     NaN  NaN                   3
5            Colorado                NaN     NaN  NaN                 NaN
6         Connecticut                  2       8   20                   3
7            Delaware                  0      10    0                   1
8             Florida                NaN     NaN  NaN                   4
9             Georgia                  9       1   90                   7
10             Hawaii                NaN     NaN  NaN                 NaN
11              Idaho                NaN     NaN  NaN                 NaN
12           Illinois                  3       0  100                  10
13            Indiana                  4       0  100                   6
14               Iowa                NaN     NaN  NaN                   3
15             Kansas                NaN     NaN  NaN                 NaN
16           Kentucky                  9       1   90                   1
17          Louisiana                  5       0  100                   7
18              Maine                  3       0  100                   6
19           Maryland                  6       4   60                   0
20      Massachusetts                  1       9   10                   0
21           Michigan                NaN     NaN  NaN                   6
22          Minnesota                NaN     NaN  NaN                 NaN
23        Mississippi                  4       0  100                   7
24           Missouri                  2       0  100                   8
25            Montana                NaN     NaN  NaN                 NaN
26           Nebraska                NaN     NaN  NaN                 NaN
27             Nevada                NaN     NaN  NaN                 NaN
28      New Hampshire                  7       3   70                   7
29         New Jersey                  8       2   80                   3
30         New Mexico                NaN     NaN  NaN                 NaN
31           New York                  6       4   60                   5
32     North Carolina                 10       0  100                   7
33       North Dakota                NaN     NaN  NaN                 NaN
34               Ohio                  8       0  100                   5
35           Oklahoma                NaN     NaN  NaN                 NaN
36             Oregon                NaN     NaN  NaN                 NaN
37       Pennsylvania                  8       2   80                   8
38       Rhode Island                  5       5   50                   2
39     South Carolina                  9       1   90                   7
40       South Dakota                NaN     NaN  NaN                 NaN
41          Tennessee                 11       0  100                   4
42              Texas                NaN     NaN  NaN                   4
43               Utah                NaN     NaN  NaN                 NaN
44            Vermont                  6       4   60                   0
45           Virginia                 10       0  100                   5
46         Washington                NaN     NaN  NaN                 NaN
47      West Virginia                NaN     NaN  NaN                 NaN
48          Wisconsin                NaN     NaN  NaN                   3
49            Wyoming                NaN     NaN  NaN                 NaN

                               Third Party System          ...  \
   AJ/W votes Other votes  % D            D votes R votes  ...
0           0           0  100                  9       3  ...
1         NaN         NaN  NaN                NaN     NaN  ...
2         NaN         NaN  NaN                NaN     NaN  ...
3           0           0  100                  9       4  ...
4           0           0  100                  6       6  ...
5         NaN         NaN  NaN                  0       7  ...
6           5           1   33                  1      11  ...
7           8           0   11                 13       1  ...
8           1           0   80                  8       3  ...
9           3           0   70                 10       1  ...
10        NaN         NaN  NaN                NaN     NaN  ...
11        NaN         NaN  NaN                  0       3  ...
12          0           0  100                  2      10  ...
13          3           0   67                  8       5  ...
14          0           1   75                  0      13  ...
15        NaN         NaN  NaN                  0      12  ...
16          9           0   10                 13       0  ...
17          3           0   70                  8       4  ...
18          3           0   66                  1      13  ...
19          9           0    0                 11       0  ...
20          8           1    0                  0      14  ...
21          1           0   86                  0      14  ...
22        NaN         NaN  NaN                  1      13  ...
23          2           0   78                  9       3  ...
24          1           0   89                 10       2  ...
25        NaN         NaN  NaN                  0       4  ...
26        NaN         NaN  NaN                  0      11  ...
27        NaN         NaN  NaN                  1      10  ...
28          1           2   70                  0      13  ...
29          6           0   33                 10       4  ...
30        NaN         NaN  NaN                NaN     NaN  ...
31          3           1   63                  3      10  ...
32          3           0   70                 10       2  ...
33        NaN         NaN  NaN                  1       3  ...
34          3           1   56                  5       8  ...
35        NaN         NaN  NaN                NaN     NaN  ...
36        NaN         NaN  NaN                  5       9  ...
37          1           0   89                  2      11  ...
38          7           0   22                  0      14  ...
39          1           2   70                  8       4  ...
40        NaN         NaN  NaN                  0       3  ...
41          5           0   44                 12       2  ...
42          0           0  100                 10       2  ...
43        NaN         NaN  NaN                NaN     NaN  ...
44          9           0    0                  0      13  ...
45          4           0   56                  9       1  ...
46        NaN         NaN  NaN                  0       4  ...
47        NaN         NaN  NaN                  8       3  ...
48          0           1   75                  2      11  ...
49        NaN         NaN  NaN                  0       4  ...

   Fifth Party System      Sixth Party System                          \
          Other votes  % D            D votes R votes Other votes % D
0                   0  100                  8       8           0  50
1                   0  100                  3      13           0  19
2                   0   75                  3      13           0  19
3                   0  100                 13       3           0  81
4                   0   33                 13       3           0  81
5                   0   50                  7       9           0  44
6                   0   67                 13       3           0  81
7                   0   33                 11       5           0  69
8                   0  100                 10       6           0  63
9                   0  100                  8       8           0  50
10                  0   40                 15       1           0  94
11                  0   50                  2      14           0  13
12                  0   58                 11       5           0  69
13                  0   50                  6      10           0  38
14                  0   33                  8       8           0  50
15                  0    8                  0      16           0   0
16                  0   67                  6      10           0  38
17                  0  100                 13       3           0  81
18                  0   17                  5      10           1  31
19                  0   67                 12       4           0  75
20                  0   42                 15       1           0  94
21                  0   42                 14       2           0  88
22                  2   50                 10       6           0  63
23                  0  100                  4      12           0  25
24                  0   83                  6      10           0  38
25                  0   92                 12       4           0  75
26                  1    8                 10       6           0  63
27                  0   83                 10       6           0  63
28                  0   17                  4      12           0  25
29                  0   33                 15       1           0  94
30                  0   92                  9       7           0  56
31                  0   58                 10       5           1  63
32                  0  100                  5      11           0  31
33                  0   17                 12       4           0  75
34                  0   50                  9       7           0  56
35                  0   92                  3      13           0  19
36                  0   33                  5      11           0  31
37                  0   42                  2      14           0  13
38                  0  100                 11       5           0  69
39                  0   92                  6      10           0  38
40                  0   17                  9       7           0  56
41                  0   92                  5      11           0  31
42                  0   92                  4      12           0  25
43                  0   58                  1      15           0   6
44                  0    0                  7       7           2  44
45                  0  100                  6       8           2  38
46                  0   92                 13       3           0  81
47                  0   92                 15       1           0  94
48                  1   33                 13       3           0  81
49                  0   67                  1      15           0   6

   Overall since 1828
              D votes R votes Other votes % D
0                  51      11           0  82
1                   8      13           0  38
2                  19      17           0  53
3                  54       7           0  89
4                  27      28           1  48
5                  20      27           1  42
6                  24      31           7  39
7                  32      31           8  45
8                  46       9           1  82
9                  49       9           3  80
10                 17       4           0  81
11                  8      33           2  19
12                 32      30           1  51
13                 30      29           3  48
14                 15      41           1  26
15                  2      49           2   4
16                 36      28           9  49
17                 52       7           3  84
18                 15      44           4  24
19                 38      13          11  61
20                 23      31           9  37
21                 26      34           1  43
22                 17      33           4  31
23                 44      15           2  72
24                 43      17           2  69
25                 33      11           0  75
26                 13      37           2  25
27                 27      22           3  52
28                 14      47           2  22
29                 35      22           6  56
30                 24      12           0  67
31                 29      29           4  47
32                 45      14           4  71
33                 15      29           0  34
34                 27      31           4  44
35                 22      16           0  58
36                 17      37           0  31
37                 17      44           1  27
38                 27      29           7  43
39                 44      15           3  71
40                 13      29           2  30
41                 44      14           5  70
42                 39      15           0  72
43                 12      29           0  29
44                  7      44          11  11
45                 44       9           9  71
46                 26      18           0  59
47                 37      14           2  70
48                 23      33           1  40
49                 12      32           0  27

[50 rows x 29 columns]

In [14]:
elect_df = elect_df.dropna(axis=1, inplace = False)
elect_df

   Unnamed: 0_level_0 Unnamed: 16_level_0 Fifth Party System          \
                State               State            D votes R votes
0             Alabama             Alabama                 12       0
1              Alaska              Alaska                  5       0
2             Arizona             Arizona                  9       3
3            Arkansas            Arkansas                 12       0
4          California          California                  4       8
5            Colorado            Colorado                  6       6
6         Connecticut         Connecticut                  8       4
7            Delaware            Delaware                  4       8
8             Florida             Florida                 12       0
9             Georgia             Georgia                 12       0
10             Hawaii              Hawaii                  2       3
11              Idaho               Idaho                  6       6
12           Illinois            Illinois                  7       5
13            Indiana             Indiana                  6       6
14               Iowa                Iowa                  4       8
15             Kansas              Kansas                  1      11
16           Kentucky            Kentucky                  8       4
17          Louisiana           Louisiana                 12       0
18              Maine               Maine                  2      10
19           Maryland            Maryland                  8       4
20      Massachusetts       Massachusetts                  5       7
21           Michigan            Michigan                  5       7
22          Minnesota           Minnesota                  6       4
23        Mississippi         Mississippi                 12       0
24           Missouri            Missouri                 10       2
25            Montana             Montana                 11       1
26           Nebraska            Nebraska                  1      10
27             Nevada              Nevada                 10       2
28      New Hampshire       New Hampshire                  2      10
29         New Jersey          New Jersey                  4       8
30         New Mexico          New Mexico                 11       1
31           New York            New York                  7       5
32     North Carolina      North Carolina                 12       0
33       North Dakota        North Dakota                  2      10
34               Ohio                Ohio                  6       6
35           Oklahoma            Oklahoma                 11       1
36             Oregon              Oregon                  4       8
37       Pennsylvania        Pennsylvania                  5       7
38       Rhode Island        Rhode Island                 12       0
39     South Carolina      South Carolina                 11       1
40       South Dakota        South Dakota                  2      10
41          Tennessee           Tennessee                 11       1
42              Texas               Texas                 11       1
43               Utah                Utah                  7       5
44            Vermont             Vermont                  0      12
45           Virginia            Virginia                 12       0
46         Washington          Washington                 11       1
47      West Virginia       West Virginia                 11       1
48          Wisconsin           Wisconsin                  4       7
49            Wyoming             Wyoming                  8       4

                    Sixth Party System                          \
   Other votes  % D            D votes R votes Other votes % D
0            0  100                  8       8           0  50
1            0  100                  3      13           0  19
2            0   75                  3      13           0  19
3            0  100                 13       3           0  81
4            0   33                 13       3           0  81
5            0   50                  7       9           0  44
6            0   67                 13       3           0  81
7            0   33                 11       5           0  69
8            0  100                 10       6           0  63
9            0  100                  8       8           0  50
10           0   40                 15       1           0  94
11           0   50                  2      14           0  13
12           0   58                 11       5           0  69
13           0   50                  6      10           0  38
14           0   33                  8       8           0  50
15           0    8                  0      16           0   0
16           0   67                  6      10           0  38
17           0  100                 13       3           0  81
18           0   17                  5      10           1  31
19           0   67                 12       4           0  75
20           0   42                 15       1           0  94
21           0   42                 14       2           0  88
22           2   50                 10       6           0  63
23           0  100                  4      12           0  25
24           0   83                  6      10           0  38
25           0   92                 12       4           0  75
26           1    8                 10       6           0  63
27           0   83                 10       6           0  63
28           0   17                  4      12           0  25
29           0   33                 15       1           0  94
30           0   92                  9       7           0  56
31           0   58                 10       5           1  63
32           0  100                  5      11           0  31
33           0   17                 12       4           0  75
34           0   50                  9       7           0  56
35           0   92                  3      13           0  19
36           0   33                  5      11           0  31
37           0   42                  2      14           0  13
38           0  100                 11       5           0  69
39           0   92                  6      10           0  38
40           0   17                  9       7           0  56
41           0   92                  5      11           0  31
42           0   92                  4      12           0  25
43           0   58                  1      15           0   6
44           0    0                  7       7           2  44
45           0  100                  6       8           2  38
46           0   92                 13       3           0  81
47           0   92                 15       1           0  94
48           1   33                 13       3           0  81
49           0   67                  1      15           0   6

   Overall since 1828
              D votes R votes Other votes % D
0                  51      11           0  82
1                   8      13           0  38
2                  19      17           0  53
3                  54       7           0  89
4                  27      28           1  48
5                  20      27           1  42
6                  24      31           7  39
7                  32      31           8  45
8                  46       9           1  82
9                  49       9           3  80
10                 17       4           0  81
11                  8      33           2  19
12                 32      30           1  51
13                 30      29           3  48
14                 15      41           1  26
15                  2      49           2   4
16                 36      28           9  49
17                 52       7           3  84
18                 15      44           4  24
19                 38      13          11  61
20                 23      31           9  37
21                 26      34           1  43
22                 17      33           4  31
23                 44      15           2  72
24                 43      17           2  69
25                 33      11           0  75
26                 13      37           2  25
27                 27      22           3  52
28                 14      47           2  22
29                 35      22           6  56
30                 24      12           0  67
31                 29      29           4  47
32                 45      14           4  71
33                 15      29           0  34
34                 27      31           4  44
35                 22      16           0  58
36                 17      37           0  31
37                 17      44           1  27
38                 27      29           7  43
39                 44      15           3  71
40                 13      29           2  30
41                 44      14           5  70
42                 39      15           0  72
43                 12      29           0  29
44                  7      44          11  11
45                 44       9           9  71
46                 26      18           0  59
47                 37      14           2  70
48                 23      33           1  40
49                 12      32           0  27

In [15]:
elect_df = elect_df.iloc[:, 1:]
elect_df.columns = elect_df.columns.get_level_values(1)

column_names2 = elect_df.columns.values
column_names2[0] = "state"
column_names2[1] = "dem_votes_1932-66"
column_names2[2] = "rep_votes_1932-66"
column_names2[3] = "other_votes_1932-66"
column_names2[4] = "percent_dem_1932-66"
column_names2[5] = "dem_votes_1968-2016"
column_names2[6] = "rep_votes_1968-2016"
column_names2[7] = "other_votes_1968-2016"
column_names2[8] = "percent_dem_votes_1968-2016"

elect_df.columns = column_names2
elect_df

,state,dem_votes_1932-66,rep_votes_1932-66,other_votes_1932-66,percent_dem_1932-66,dem_votes_1968-2016,rep_votes_1968-2016,other_votes_1968-2016,percent_dem_votes_1968-2016,D votes,R votes,Other votes,% D
0,Alabama,12,0,0,100,8,8,0,50,51,11,0,82
1,Alaska,5,0,0,100,3,13,0,19,8,13,0,38
2,Arizona,9,3,0,75,3,13,0,19,19,17,0,53
3,Arkansas,12,0,0,100,13,3,0,81,54,7,0,89
4,California,4,8,0,33,13,3,0,81,27,28,1,48
5,Colorado,6,6,0,50,7,9,0,44,20,27,1,42
6,Connecticut,8,4,0,67,13,3,0,81,24,31,7,39
7,Delaware,4,8,0,33,11,5,0,69,32,31,8,45
8,Florida,12,0,0,100,10,6,0,63,46,9,1,82
9,Georgia,12,0,0,100,8,8,0,50,49,9,3,80
10,Hawaii,2,3,0,40,15,1,0,94,17,4,0,81
11,Idaho,6,6,0,50,2,14,0,13,8,33,2,19
12,Illinois,7,5,0,58,11,5,0,69,32,30,1,51
13,Indiana,6,6,0,50,6,10,0,38,30,29,3,48
14,Iowa,4,8,0,33,8,8,0,50,15,41,1,26
15,Kansas,1,11,0,8,0,16,0,0,2,49,2,4
16,Kentucky,8,4,0,67,6,10,0,38,36,28,9,49
17,Louisiana,12,0,0,100,13,3,0,81,52,7,3,84
18,Maine,2,10,0,17,5,10,1,31,15,44,4,24
19,Maryland,8,4,0,67,12,4,0,75,38,13,11,61
20,Massachusetts,5,7,0,42,15,1,0,94,23,31,9,37
21,Michigan,5,7,0,42,14,2,0,88,26,34,1,43
22,Minnesota,6,4,2,50,10,6,0,63,17,33,4,31
23,Mississippi,12,0,0,100,4,12,0,25,44,15,2,72
24,Missouri,10,2,0,83,6,10,0,38,43,17,2,69
25,Montana,11,1,0,92,12,4,0,75,33,11,0,75
26,Nebraska,1,10,1,8,10,6,0,63,13,37,2,25
27,Nevada,10,2,0,83,10,6,0,63,27,22,3,52
28,New Hampshire,2,10,0,17,4,12,0,25,14,47,2,22
29,New Jersey,4,8,0,33,15,1,0,94,35,22,6,56
30,New Mexico,11,1,0,92,9,7,0,56,24,12,0,67
31,New York,7,5,0,58,10,5,1,63,29,29,4,47
32,North Carolina,12,0,0,100,5,11,0,31,45,14,4,71
33,North Dakota,2,10,0,17,12,4,0,75,15,29,0,34
34,Ohio,6,6,0,50,9,7,0,56,27,31,4,44
35,Oklahoma,11,1,0,92,3,13,0,19,22,16,0,58
36,Oregon,4,8,0,33,5,11,0,31,17,37,0,31
37,Pennsylvania,5,7,0,42,2,14,0,13,17,44,1,27
38,Rhode Island,12,0,0,100,11,5,0,69,27,29,7,43
39,South Carolina,11,1,0,92,6,10,0,38,44,15,3,71
40,South Dakota,2,10,0,17,9,7,0,56,13,29,2,30
41,Tennessee,11,1,0,92,5,11,0,31,44,14,5,70
42,Texas,11,1,0,92,4,12,0,25,39,15,0,72
43,Utah,7,5,0,58,1,15,0,6,12,29,0,29
44,Vermont,0,12,0,0,7,7,2,44,7,44,11,11
45,Virginia,12,0,0,100,6,8,2,38,44,9,9,71
46,Washington,11,1,0,92,13,3,0,81,26,18,0,59
47,West Virginia,11,1,0,92,15,1,0,94,37,14,2,70
48,Wisconsin,4,7,1,33,13,3,0,81,23,33,1,40
49,Wyoming,8,4,0,67,1,15,0,6,12,32,0,27

In [16]:
elect_df = elect_df[["state", "dem_votes_1968-2016", "rep_votes_1968-2016", 
                    "other_votes_1968-2016", "percent_dem_votes_1968-2016"]]

elect_df

,state,dem_votes_1968-2016,rep_votes_1968-2016,other_votes_1968-2016,percent_dem_votes_1968-2016
0,Alabama,8,8,0,50
1,Alaska,3,13,0,19
2,Arizona,3,13,0,19
3,Arkansas,13,3,0,81
4,California,13,3,0,81
5,Colorado,7,9,0,44
6,Connecticut,13,3,0,81
7,Delaware,11,5,0,69
8,Florida,10,6,0,63
9,Georgia,8,8,0,50
10,Hawaii,15,1,0,94
11,Idaho,2,14,0,13
12,Illinois,11,5,0,69
13,Indiana,6,10,0,38
14,Iowa,8,8,0,50
15,Kansas,0,16,0,0
16,Kentucky,6,10,0,38
17,Louisiana,13,3,0,81
18,Maine,5,10,1,31
19,Maryland,12,4,0,75
20,Massachusetts,15,1,0,94
21,Michigan,14,2,0,88
22,Minnesota,10,6,0,63
23,Mississippi,4,12,0,25
24,Missouri,6,10,0,38
25,Montana,12,4,0,75
26,Nebraska,10,6,0,63
27,Nevada,10,6,0,63
28,New Hampshire,4,12,0,25
29,New Jersey,15,1,0,94
30,New Mexico,9,7,0,56
31,New York,10,5,1,63
32,North Carolina,5,11,0,31
33,North Dakota,12,4,0,75
34,Ohio,9,7,0,56
35,Oklahoma,3,13,0,19
36,Oregon,5,11,0,31
37,Pennsylvania,2,14,0,13
38,Rhode Island,11,5,0,69
39,South Carolina,6,10,0,38
40,South Dakota,9,7,0,56
41,Tennessee,5,11,0,31
42,Texas,4,12,0,25
43,Utah,1,15,0,6
44,Vermont,7,7,2,44
45,Virginia,6,8,2,38
46,Washington,13,3,0,81
47,West Virginia,15,1,0,94
48,Wisconsin,13,3,0,81
49,Wyoming,1,15,0,6

In [17]:
senate2018_df = pd.read_csv('senate2018.csv', encoding='cp1252')
senate2018_df

,1,STATE ABBREVIATION,STATE,DISTRICT,FEC ID#,(I),CANDIDATE NAME (First),CANDIDATE NAME (Last),CANDIDATE NAME,TOTAL VOTES,...,GENERAL VOTES,GENERAL %,GE RUNOFF ELECTION VOTES (MS Senate),GE RUNOFF ELECTION % (MS Senate),"COMBINED GE PARTY TOTALS (CT, NY)","COMBINED % (CT, NY)",GE WINNER INDICATOR,FOOTNOTES,Unnamed: 23,Unnamed: 24
0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3.0,AZ,Arizona,S,S8AZ00197,NaN,Kyrsten,Sinema,"Sinema, Kyrsten",NaN,...,"1,191,100",49.96%,NaN,NaN,NaN,NaN,W,NaN,NaN,NaN
2,4.0,AZ,Arizona,S,S8AZ00122,NaN,Deedra,Abboud,"Abboud, Deedra",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5.0,AZ,Arizona,S,NaN,NaN,NaN,NaN,NaN,Party Votes:,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6.0,AZ,Arizona,S,S8AZ00221,NaN,Martha,McSally,"McSally, Martha",NaN,...,"1,135,200",47.61%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
631,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
632,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
633,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
senate2018_df.columns

Index(['1', 'STATE ABBREVIATION', 'STATE', 'DISTRICT', 'FEC ID#', '(I)',
       'CANDIDATE NAME (First)', 'CANDIDATE NAME (Last)', 'CANDIDATE NAME',
       'TOTAL VOTES', 'PARTY', 'PRIMARY VOTES', 'PRIMARY %', 'RUNOFF VOTES',
       'RUNOFF %', 'GENERAL VOTES ', 'GENERAL %',
       'GE RUNOFF ELECTION VOTES (MS Senate)',
       'GE RUNOFF ELECTION % (MS Senate)', 'COMBINED GE PARTY TOTALS (CT, NY)',
       'COMBINED % (CT, NY)', 'GE WINNER INDICATOR', 'FOOTNOTES',
       'Unnamed: 23', 'Unnamed: 24'],
      dtype='object')

In [19]:
senate2018_df = senate2018_df[['STATE', 'PARTY', 'GE WINNER INDICATOR']]
senate2018_df

       STATE PARTY GE WINNER INDICATOR
0        NaN   NaN                 NaN
1    Arizona     D                   W
2    Arizona     D                 NaN
3    Arizona     D                 NaN
4    Arizona     R                 NaN
..       ...   ...                 ...
629      NaN   NaN                 NaN
630      NaN   NaN                 NaN
631      NaN   NaN                 NaN
632      NaN   NaN                 NaN
633      NaN   NaN                 NaN

[634 rows x 3 columns]

In [20]:
senate2018_df = senate2018_df.dropna()
senate2018_df = senate2018_df.reset_index()
senate2018_df = senate2018_df[['STATE', 'PARTY']]
senate2018_df

            STATE PARTY
0         Arizona     D
1      California     D
2     Connecticut     D
3        Delaware     D
4         Florida     R
5          Hawaii     D
6         Indiana     R
7           Maine   IND
8        Maryland     D
9   Massachusetts     D
10       Michigan     D
11      Minnesota   DFL
12      Minnesota   DFL
13    Mississippi     R
14    Mississippi     N
15       Missouri     R
16        Montana     D
17       Nebraska     R
18         Nevada     D
19     New Jersey     D
20     New Mexico     D
21       New York     D
22   North Dakota     R
23           Ohio     D
24   Pennsylvania     D
25   Rhode Island     D
26      Tennessee     R
27          Texas     R
28           Utah     R
29        Vermont   IND
30       Virginia     D
31     Washington     D
32  West Virginia     D
33      Wisconsin     D
34        Wyoming     R

In [21]:
#senate2018_url = 'https://en.wikipedia.org/wiki/2018_United_States_Senate_elections'

#senate2018_df = pd.read_html(senate2018_url)[9]

#senate2018_df

In [22]:
#senate2018_df.columns = senate2018_df.columns.get_level_values(1)
#senate2018_df = senate2018_df[["State", "Result"]]

#column_names3 = senate2018_df.columns.values
#column_names3[0] = "state"
#column_names3[1] = "result"


#senate2018_df.columns = column_names3

#senate2018_df['result'] = senate2018_df['result'].astype(str)
#senate2018_df

In [23]:
#senate2018_df = senate2018_df.head(35)
#senate2018_df

In [24]:
#senate2018_list = {}

#for i in senate2018_df:

In [25]:
#senate2018_df.dtypes

In [26]:
import psycopg2
import sqlalchemy
import matplotlib as plt

%matplotlib inline

In [27]:
from sqlalchemy import create_engine

In [28]:
postgresStr = "postgresql://postgres:password@localhost:5433/representation_db"
engine = create_engine(postgresStr)
conn = engine.connect()

print(engine.table_names())

['elections', 'representation', 'funding']

In [29]:
representation_df.to_sql('representation', conn)
funding_df.to_sql('funding', conn)
elect_df.to_sql('elections', conn)

print('Success')

ValueError: Table 'representation' already exists.